### ISSUE TITLE
Uninitialized `dtype` value used in expression.

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#1006]
https://github.com/flang-compiler/flang/blob/5c1ba32861a60f12f32120cb3c239f4e13088296/tools/flang1/flang1exe/lowersym.c#L5423
```
    int dtype;
    int ent_dtype = DTYPEG(sptr);
    llvm_fix_args(sptr, dtype != DT_NONE);
    dtype = DTYPEG(fval);
```
@mleair `dtype` variable is used uninitialized in the `llvm_fix_args(sptr, dtype != DT_NONE);` expression. Question: was `ent_dtype` supposed to be used in the `dtype != DT_NONE` expression instead, or the next line `dtype = DTYPEG(fval);` should go before `llvm_fix_args(sptr, dtype != DT_NONE);`?

**Comment by pawosm-arm** [comment]
The answer to my question above is: none. This parameter is not needed in a first place. I've prepared PR with a patch which removes it.

**Comment by mleair** [comment]
Yes, it appears the second argument to llvm_fix_args() is not used. It's probably best to just removed the unused argument. I assume that is the route you are going. :)

**Comment by pawosm-arm** [comment]
the change is now merged to master
