### ISSUE TITLE
Please distinguish this repository from LLVM flang in the README.md or repository name

### ISSUE THREAD

**Issue by rouson** [flang-compiler/flang#1027]
When I perform a Google search on "flang," this repository is the first result.  Based on this [issue comment], it appears that this code will eventually be replaced by LLVM flang.  It would be great if the top-level README.md made that clear at the top of the document.  Even better might be to also rename the repository to something like "classic-flang," but I imagine that would be a much less popular move if there's active development by many developers.  Either way, I think it would be great to eliminate confusion for those who land here in a web search.

[issue comment](https://github.com/flang-compiler/flang/issues/1022#issuecomment-812896085)

**Comment by bryanpkc** [comment]
I thought of the same thing the other day when reading the README. I will create a PR to update it.
