### ISSUE TITLE
Regression (string not displayed) after PR#1009

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#1059]
Following Fortran program has changed its behavior after PR#1009:
```
program testsize
  implicit none
  character(:), pointer :: ptr(:, :)
  type t1
    character(:), pointer :: ptr(:)
  end type t1
  type(t1) :: var
  call setup(var, ptr)
  call runtest(var, ptr)

contains

  subroutine setup(var, ptr)
    implicit none
    character(:), pointer :: ptr(:, :)
    type(t1) var

    allocate(var%ptr(1), source="hello world")
    allocate(ptr(1,3), source="hello")
  end subroutine setup

  subroutine runtest(var, ptr)
    implicit none
    character(:),pointer :: ptr(:, :)
    type(t1) var
    integer :: i

    print *, var%ptr
    print *, var%ptr(1)
    print *, var%ptr(size(var%ptr, 1) : 1 : -1)
    print *, var%ptr((/ (i, i = 1, size(var%ptr)) /))
    print *, ptr
  end subroutine runtest

end program testsize
```

When outputed to a text file, this program should produce the following output:
```
 hello world 
 hello world
 hello world
 hellohellohello
```

After merging PR#1009, only `hellohellohello` is ever displayed.

As PR#1009 consists of two commits, I've narrowed the problem to a single particular commit: `[flang1] Pass descriptor flags to RTE_template correctly`.

**Comment by bryanpkc** [comment]
@pawosm-arm On X86, using a build before or without the problematic patch (at commit 1c7ab2201713, or after reverting e03b499152a5 from master branch), I observe a different behaviour.

In my runs, the program produces **five** lines of output in total, with the each of the first four lines consisting of "hello" followed by 65534 spaces. The last line of output remains "hellohellohello". Inside `runtest`, `size(var%ptr)` is 1.

I am not sure how `var%ptr` got initialized with so many extra spaces. `allocate` with a `source` should have set the string to "hello world". Investigating further.

**Comment by bryanpkc** [comment]
As I said above, the original behaviour was wrong. @PeixinQiao will submit a PR shortly.

**Comment by PeixinQiao** [comment]
Before PR#1009, the breakpoint is set at function convert_template_instance in outconv.c, and the type descriptor set statements for allocate(var%ptr(1), source="hello world") are dumped as follows:
```
(gdb) p dsstds(0,0)
subprogram 2 setup:
std:1    ast:172   lineno:18          var%ptr$sd(11_8) = 1_8
std:2    ast:173   lineno:18          var%ptr$sd(12_8) = 1_8
std:4    ast:185   lineno:18          var%ptr$sd(4_8) = 11_8
std:25   ast:244   lineno:18          call f90_template_i8(var%ptr$sd,1_8,0_8,0_8,65538_8,var%ptr$sd(11_8),var%ptr$sd(11_8) + (var%ptr$sd(12_8) - 1_8))
std:26   ast:248   lineno:18          call f90_set_intrin_type_i8(var%ptr$sd,%val(14))
std:27   ast:256   lineno:18          call fort_instance_i8(var%ptr$sd,var%ptr$sd,14_8,f90_lena(var%ptr),0_8)
std:28   ast:257   lineno:18          call f90_set_intrin_type_i8(var%ptr$sd,%val(14))
std:3    ast:181   lineno:18          allocate(var%ptr(var%ptr$sd(11_8):var%ptr$sd(11_8)+(var%ptr$sd(12_8)-1_8)), source='hello world', firstalloc)
```
The `length` info for `var%ptr$sd` is set incorrectly as 65538, which should be the `FLAG` value. Tested on aarch64 and the output for the first four lines is `hello world` followed by 65527 spaces.

PR#1098 is proposed to solve this problem.

**Comment by pawosm-arm** [comment]
Seems to work now.
