### ISSUE TITLE
Internal compiler error. Unsafe type for inttoptr      32

### ISSUE THREAD

**Issue by burp** [flang-compiler/flang#114]
Hi,

it looks like there is an issue when you combine omp threadprivate common blocks with alternate returns of subroutines. At least that is what I boiled this error down to in the following example. flang as built by the README with llvm 3.9 crashes as follows:

% flang -fopenmp -o test flang.f 
F90-F-0000-Internal compiler error. Unsafe type for inttoptr      32 (flang.f: 15)
F90/x86-64  Flang - 1.5 2017-05-01: compilation aborted

The code I use is:

       program hello
        implicit none

        print *, 'hello world'
      end

      subroutine hello(p,*)
        implicit none
        real p
        real :: cutoff
        common/cutoff_common/cutoff
!$omp threadprivate(/cutoff_common/)

        return 1
      end subroutine

If you remove the alternate return (*) it compiles again. If you remove the omp threadprivate it compiles again.

**Comment by gklimowicz** [comment]
Fixed with commit 45c4cc8
