### ISSUE TITLE
POWER Supported?

### ISSUE THREAD

**Issue by AndiH** [flang-compiler/flang#116]
I (after a few unsuccessful attempts) managed to compile flang on a POWER8 system.
Unfortunately, the README.md-mentioned *Hello World* does not compile:

```
$ flang hello.f90
/gpfs/homeb/zam/aherten/opt/software/llvm+flang/3.9/bin/../lib/libflang.so: undefined reference to `llvm.ppc.vsx.xsnmsubadp'
/gpfs/homeb/zam/aherten/opt/software/llvm+flang/3.9/bin/../lib/libflang.so: undefined reference to `llvm.ppc.vsx.xsmaddadp'
/gpfs/homeb/zam/aherten/opt/software/llvm+flang/3.9/bin/../lib/libflang.so: undefined reference to `llvm.ppc.vsx.xsmaddasp'
/gpfs/homeb/zam/aherten/opt/software/llvm+flang/3.9/bin/../lib/libflang.so: undefined reference to `llvm.ppc.vsx.xsnmsubasp'
```

Did I do something wrong? Is this a bug? Is the POWER architecture supported at all?

**Comment by sscalpone** [comment]
You did nothing wrong.  We expect POWER to be supported.  We are working on upstreaming the changes to support llvm.ppc.vsx.* for POWER.  In the meantime, we'll push a change to work around the problem.  If you want a quick workaround, you might be able to add -nofma to the compilation options that are used to build libflang.so.  (I did not try that workaround.)

**Comment by AndiH** [comment]
Thanks for the info!

I can't find how to add the `-nofma` flag. By using `-DCMAKE_Fortran_FLAGS="-nofma"` not. And in the CMakeLists.txt I can't see where the file is created.

**Comment by sscalpone** [comment]
I just merged a change that disables generation of  llvm.ppc.vsx.* for POWER.

**Comment by AndiH** [comment]
```
$ ./a.out
 hello world
```
Your changes work! Thank you very much for the quick fix.

Are you planning to eventually support the instructions again at some point?

**Comment by sscalpone** [comment]
LLVM for OpenPOWER supports fma; flang might generate those now just using its default mechanisms. I don't know.  We are preparing to contribute changes to llvm.org; I'm not sure on the timing of those changes.
