### ISSUE TITLE
Q: Compiler message structure for VS Code integration

### ISSUE THREAD

**Issue by gnikit** [flang-compiler/flang#1176]
Hi all,

We are finally getting around to adding linting support for `flang` in VS Code [`Modern Fortran`](https://github.com/krvajal/vscode-fortran-support) . How we achieve that is through a syntax only compilation of the files with `-fsyntax-only` and then using regex we extract the relevant parts from stdout/stderr. For that we need to have a good understanding of the structure of the compiler messages, e.g. warnings, errors, fatal errors,etc. .

Hence, I was wondering if you could point me to a resource or provide an outline for `flang`'s compiler output. Here is an example of what I am looking for from [Intel's `(ifort)`](https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/compiler-reference/error-handling/handling-compile-time-errors/understanding-errors-during-the-build-process.html) compiler. Similarly, for `gfortran` most compiler messages fit this pattern:

```log
filename:line:column:
      
  line |  failing line of code
       |
severity: message
```

Using the following MWE as a testbed 

```fortran
program main

  call say_hello(1, 1)

contains

  subroutine say_hello(a,b)
    integer :: a,b

    print *, "Hello, World!"
  end subroutine say_hello

end program main
```
and compiling with `flang -Wall -fsyntax-only sample.f90` I would expect some warnings to be raised for the unused variables `a` and `b` but only a warning is thrown for `-Wall` being unused. Am I missing something?

Replacing `call say_hello(1,1)` in the above MWE with `call say_hello()` to raise a compile time error yields the message:

```log
F90-S-0186-Argument missing for formal argument a (sample.f90: 3)
  0 inform,   0 warnings,   1 severes, 0 fatal for main
```

This message we can work with, but is there a way to also get the column number where the error occurred?

On a related note, I understand that there are effectively 2 `flang` compilers this one and formerly known `f18` which is now a part of the `llvm-project`. Do you know if the compiler output from `f18` is different from this repos `flang` output and if so, how? Again, any links to docs would be greatly appreciated.

## Additional information

```bash
flang --version
```
output:
```log
clang version 7.0.1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by bryanpkc** [comment]
Sorry for neglecting this issue. The Classic Flang frontend uses a fairly primitive framework for producing diagnostics, and some components print free-style messages without adhering to a strict formatting guideline. I am not sure if there is a general mechanism for tracking and reporting the column number when parse errors occur. Warning and error options (`-W` and `-Werror`) are accepted by the driver but not actually supported in the frontend, because the frontend is not well-integrated with LLVM.

The new LLVM Flang (F18) can and probably already does support what you need. I'll close this issue now.
