### ISSUE TITLE
Cannot run the bitcode

### ISSUE THREAD

**Issue by htg20** [flang-compiler/flang#120]
Hello,

For the hello world  example, the normal executable works. However, when I do 
flang  -emit-llvm   hello.f90 -c -o   hello.bc

and try to run using lli  ( lli hello.bc), I get the error message:

'main' function not found in module.

In case of C++, this works as expected. What am I missing here?

**Comment by sscalpone** [comment]
The name of a main program in flang is MAIN_. 

I was able to run hello.f90 with this command (where $flang is my install directory):

 $flang/bin/lli  -entry-function=MAIN_  -load=$flang/lib/libflangrti.so -load=$flang/lib/libflang.so hello.bc
 hello world from from hello.f90

**Comment by htg20** [comment]
Thank you, worked also for me.

BTW, do you know of any effort to make flang work with Emscripten?

**Comment by sscalpone** [comment]
No idea about Emscripten.
