### ISSUE TITLE
Please support llvm-4.0

### ISSUE THREAD

**Issue by yurivict** [flang-compiler/flang#122]
I tried to build and run with llvm-4.0 on the FreeBSD and it works fine.
Unless there are specific llvm-4.0-related failures, please update the supported version.

**Comment by schweitzpgi** [comment]
You're correct. Flang should work fine with LLVM 4.0 "out of the box".

**Comment by sscalpone** [comment]
Instructions updated 28c33f8b9e79731f0f7e9b1f0af12a2cba2af563
