### ISSUE TITLE
error: unable to execute command: Executable "flang1" doesn't exist!

### ISSUE THREAD

**Issue by HengyueLi** [flang-compiler/flang#124]
OS: Fedora 25

!----[start test.f90]----------------------
program main
      write(\*,\*)"ok"
end
!----[end test.f90]----------------------
$ flang test.f90
clang-3.9: error: unable to execute command: Executable "flang1" doesn't exist!

**Comment by sscalpone** [comment]
Hi.  Does flang1 exist in your install/bin directory?  Did you build with cmake -DCMAKE_INSTALL_PREFIX?  Can you include the output of flang -v test.f90?

**Comment by ggyyuuuu** [comment]
Sorry, this is the first time to use GitHub, and also I am not expert of Linux. Thus I am not so sure if I have your questions clearly understood.
1. I mkdir GitHub at ~/GitHub and download everything from this web into that folder. Thus I have "~/GitHub/clang","~/GitHub/flang","~/GitHub/llvm" and "~/GitHub/openmp". 
2. I have followed the instructions 1-4  it the web.
3. After the problem happend, I check the folder ~/GitHub/flang/tools/flagn1/flang1exe/, in which there are many *.c and *.h
4.In terminal when I type "fla" and press "Tab", I can found flang but no flang1.

**Comment by sscalpone** [comment]
(1). Do you mean that in each step in 1-4 when we cmake, we need to use the command "cmake -DCMAKE_INSTALL_PREFIX" ?  YES

(2) Do you see InstallDir is /usr/local/bin.  Do you see flang1 in that directory?   When you type "make install" for flang, to where are the files copied?

**Comment by ggyyuuuu** [comment]
(1). For example, the 1/4 step (install LLVM), when I tap "cmake -DCMAKE_INSTALL_PREFIX .." instead "cmake ..", error feedback is : 
Parse error in command line argument: -DCMAKE_INSTALL_PREFIX
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.
(2). I do not find flang1 there(while flang is existed).
In that step, the printing contains something like:
"[ 36%] Linking C executable ../../../bin/flang1" and "[ 36%] Building C object tools/flang1/flang1exe/CMakeFiles/flang1.dir/vsub.c.o" .
So where are they? -_-!

**Comment by sscalpone** [comment]
Hi @HengyueLi -- Please reopen this issue if you still want to discuss it.  Thanks!
