### ISSUE TITLE
Flang error during compilation in macos mojave

### ISSUE THREAD

**Issue by uNouss** [flang-compiler/flang#1240]
## Step to reproduce
- follow instructions from here: https://github.com/flang-compiler/flang/wiki/Building-Flang#step-by-step-instructions
- In `step-3`: during this command `cmake $CMAKE_OPTIONS -DFLANG_LLVM_EXTENSIONS=ON ..`. I encounter this issue 
```bash
-- Found LLVM_CONFIG as /Users/User/llvm/install/bin/llvm-config
CMake Error at /Users/User/llvm/install/lib/cmake/llvm/CheckCompilerVersion.cmake:97 (message):
  libstdc++ version must be at least 5.1.
Call Stack (most recent call first):
  /Users/User/llvm/install/lib/cmake/llvm/HandleLLVMOptions.cmake:9 (include)
  CMakeLists.txt:151 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/User/llvm/flang/build/CMakeFiles/CMakeOutput.log".
See also "/Users/User/llvm/flang/build/CMakeFiles/CMakeError.log".
```
The eror log files and others files are here: https://gist.github.com/uNouss/7b831b58bb2a9447dc8a5a1772ed5553

**Comment by bryanpkc** [comment]
Sorry for the late response, but did you try installing the libstdc++ package on your operating system? We don't have macOS hardware to test with, but I know some other folks have done this before.

If you don't care any more, please close the issue.

**Comment by bryanpkc** [comment]
Closing stale issue.
