### ISSUE TITLE
Building current classic flang

### ISSUE THREAD

**Issue by justxi** [flang-compiler/flang#1241]
Hello,

I would like to build classic flang. 

In https://github.com/flang-compiler/flang/wiki there is mentioned that "flang" consists of three projects.
In https://github.com/flang-compiler/flang/wiki/Building-Flang I see only "classic-flang-llvm-project" and "flang" repositories.
Is the driver not needed?

And the "flang" repository has only a "master" branch (besides some revert branches). The "classic-flang-llvm-project"  repository has release branches up to 14. Is it possible to build the "flang" repository against all "classic-flang-llvm-project" branches?

**Comment by bryanpkc** [comment]
@justxi  I have updated the first wiki page to remove the reference to the stale "flang-driver" repository. Its functionality is now included in the "classic-flang-llvm-project" repository.

The master branch of the "flang" repository can be built on the "release_12x" and "release_13x" branches of "classic-flang-llvm-project". "release_11x" and older branches are no longer supported.

**Comment by justxi** [comment]
Ok, I will try to build it.
Thanks for your information.

**Comment by Neumann-A** [comment]
small hint

it is not:
`-DLLVM_ENABLE_CLASSIC_FLANG=ON -DLLVM_ENABLE_PROJECTS="clang;openmp"`
but:
`-DLLVM_ENABLE_CLASSIC_FLANG=ON -DLLVM_ENABLE_PROJECTS="clang;openmp;flang"`

**Comment by bryanpkc** [comment]
@Neumann-A  Actually, when building Classic Flang, you should not enable the "flang" project when building LLVM; that project refers to the new LLVM Flang frontend, which is different from Classic Flang.

**Comment by bryanpkc** [comment]
https://github.com/flang-compiler/classic-flang-llvm-project/blob/release_13x/clang/tools/driver/CMakeLists.txt#L62 ensures that a symbolic link is created for `flang` when building the Classic Flang flavour of llvm-project.
