### ISSUE TITLE
A zero-length array should be illegal when the array is intended to be interoperable

### ISSUE THREAD

**Issue by bryanpkc** [flang-compiler/flang#1249]
Originally posted by @pawosm-arm, in https://github.com/flang-compiler/flang/pull/1129#discussion_r861131369, regarding:

https://github.com/flang-compiler/flang/blob/46ec115bed6c8f9b99f5a6163163d8e297ba751d/tools/flang1/flang1exe/semant.c#L6186

> @bryanpkc can you explain the rationale behind that change? Looks like now flang has stopped to warn about zero-sized arrays. There is a nag test (z2a.f90) which expect a compiler to warn about zero sized array and now this test fails as flang accepts such array silently.

Response by @bryanpkc:

> @pawosm-arm I believe this was done in our downstream compiler to make its behavior consistent with both gfortran and ifort, which do not produce any error when an C-interoperable array has a size of zero (https://godbolt.org/z/Pe1bMxdzz), despite the wording in the Fortran 2008 specification (section 15.3.6, *Interoperability of array variables*).

## Problem

Section 15.3.6 states (emphasis in bold mine):

> An explicit-shape or assumed-size array of rank r, with a shape of <code>[ e<sub>1</sub> ... e<sub>r</sub> ]</code> is interoperable with a C array if its size is **nonzero** and
> 1. either
>     <ol type="a">
>     <li>the array is assumed-size, and the C array does not specify a size, or</li>
>     <li>the array is an explicit-shape array, and the extent of the last dimension (<code>e<sub>r</sub></code>) is the same as the size of the C array, and</li>
>     </ol>
> 2. either
>     <ol type="a">
>     <li><code>r</code> is equal to one, and an element of the array is interoperable with an element of the C array, or</li>
>     <li><code>r</code> is greater than one, and an explicit-shape array with shape of <code>[ e<sub>1</sub> ... e<sub>r-1</sub> ]</code>, with the same type and type parameters as the original array, is interoperable with a C array of a type equal to the element type of the original C array.</li>
>     </ol>

For normal Fortran arrays that are not interoperable, there is no such restriction. Section 5.3.8.2 (*Explicit-shape array*) specifically allows zero-length arrays:

> The value of a lower bound or an upper bound may be positive, negative, or zero. The subscript range of the array in that dimension is the set of integer values between and including the lower and upper bounds, provided the upper bound is not less than the lower bound. If the upper bound is less than the lower bound, the range is empty, the extent in that dimension is zero, and the array is of zero size.

Currently, the semantic check of an array's upper bound ignores whether the array needs to be interoperable. Before PR #1129, Flang would always complain about a zero-length array. After PR #1129 introduced the above-mentioned change by accident, Flang now always allows a zero-length array. To fix this problem properly, IIUC, we need to detect whether an array specification has the `BIND(C)` attribute, or if not, whether any derived type of which the current array is a member has the `BIND(C)` attribute. I tried looking but haven't found any existing code that performs a similar check.

**Comment by pawosm-arm** [comment]
The compatibility with the behavior of the widely used compilers is a good rationale behind leaving things as they are now. In this case, the cost of messing with flang's semantic analysis will be higher than potential gain, therefore I'm opting for adding this test case to a denylist and closing the issue (even if I raised it initially).

**Comment by bryanpkc** [comment]
As discussed at the biweekly call, we have agreed to keep the current behaviour (be consistent with other compilers), and close this issue.
