### ISSUE TITLE
Fails to build SLATEC Common Mathematical Library: Instruction does not dominate all uses!

### ISSUE THREAD

**Issue by yurivict** [flang-compiler/flang#129]
```
flang   -O -c genbun.f -o genbun.o
Instruction does not dominate all uses!
  %.pre126 = sext i32 %64 to i64, !dbg !100
  %208 = shl nsw i64 %.pre126, 2, !dbg !99
fatal error: error in backend: Broken function found, compilation aborted!
clang-3.9: error: clang frontend command failed with exit code 70 (use -v to see invocation)
```

slatec-4.1

**Comment by iotamudelta** [comment]
@yurivict you should probably append the source file. Are you sure this is not FreeBSD-specific?

**Comment by yurivict** [comment]
Source: http://netlib.sandia.gov/fishpack/genbun.f

IMO, flang writes an invalid module with -O flag. This shouldn't be FreeBSD-specific.

**Comment by sscalpone** [comment]
The problem is not specific to FreeBSD.  I've reproduced Ubuntu.

**Comment by schweitzpgi** [comment]
I've reduced the bug and submitted it.

https://bugs.llvm.org/show_bug.cgi?id=33731

**Comment by yurivict** [comment]
"Instruction does not dominate all uses!" is in general a valid error. You need to explain in the llvm bug report why is it issued wrong in this case.

**Comment by gklimowicz** [comment]
This works with the current version of Flang built with LLVM 6.0.1.

Please reopen if you continue to find problems with updated LLVM.
