### ISSUE TITLE
flang cannot build hdf5

### ISSUE THREAD

**Issue by nuitlejour** [flang-compiler/flang#1305]
I have installed llvm compiler toolchain (version 14.0.5), including clang, flang, etc., on my Fedora 36 operating system and downloaded the latest hdf5-1.12.2 from https://www.hdfgroup.org/downloads/hdf5/

From the source folder I executed the following commands to compile the hdf:
export CC=clang
export FC=flang
./configure --enable-fortran 

during configuration process, the following error occurred:
...
checking if Fortran interface enabled... yes
checking whether we are using the GNU Fortran compiler... no
checking whether flang accepts -g... yes
checking for Fortran flag to compile .f90 files... none
checking whether we are using the GNU Fortran compiler... (cached) no
checking whether flang accepts -g... (cached) yes
checking what flang does with modules... MODULE.mod
checking how flang finds modules... -I
checking if Fortran compiler version compatible with Fortran 2003 HDF... no
configure: error: Fortran compiler lacks required Fortran 2003 features; unsupported Fortran 2003 compiler, remove --enable-fortran

I'm not sure if it is indeed something wrong with flang, or different configuration I should use.

**Comment by nuitlejour** [comment]
also I have tried building netcdf-fortran using flang, during compilation, the follow error occured:

error: Semantic errors in conftest.f90
./conftest.f90:2:5: error: Cannot read module file for module 'iso_c_binding': Source file 'iso_c_binding.f18.mod' was not found
  USE ISO_C_BINDING, ONLY: C_PTRDIFF_T
      ^^^^^^^^^^^^^
flang: in /mnt/d/Work/netcdf4/netcdf-fortran-4.6.0, flang-new failed with exit status 1: /usr/bin/flang-new -fc1 -module-suffix .f18.mod -fdebug-unparse -fno-analyzed-objects-for-unparse -c -g conftest.f90
configure:7936: $? = 1
configure:7945: result: no
configure:7949: error: in `/mnt/d/Work/netcdf4/netcdf-fortran-4.6.0':
configure:7951: error: Can't use build F03 interfaces

I suspect the problem arise from flang implementation of fortran 2003 iso_c_binding intrinsic function.

**Comment by nuitlejour** [comment]
similar issue:
https://github.com/flang-compiler/f18/issues/318

**Comment by nuitlejour** [comment]
flang does not support iso_c_binding intrinsic module as of now?

**Comment by bryanpkc** [comment]
@nuitlejour This issue tracker is for Classic Flang, which is different from LLVM Flang (`flang-new`). Classic Flang should support `iso_c_binding`. Please take a look at the wiki page below to learn how to build Classic Flang:

https://github.com/flang-compiler/flang/wiki/Building-Flang
