### ISSUE TITLE
ppc/ppc64 support?

### ISSUE THREAD

**Issue by barracuda156** [flang-compiler/flang#1309]
I see that only ppc64le is featured in CMakeLists. What is needed to implement ppc and ppc64 support?

**Comment by bryanpkc** [comment]
ppc64le support has not been tested in a long time, so it may not work completely. Porting to ppc64 is probably doable; we did it for riscv64 (not upstreamed) previously. You could take a look at some of the architecture-specific files and directories under `tools/flang2/flang2exe/` to get started. A bigger problem is that you will need to fix little-endian assumptions throughout the frontend (especially in constant construction and folding) and the runtime.

Classic Flang probably ran on 32-bit x86 a long time ago, but nowadays the assumption is that we only target 64-bit architectures, so porting to ppc will probably require more work.

**Comment by pawosm-arm** [comment]
I'm closing it as none of the active maintainers have capability to proceed with this one. The volunteers are more than welcomed though, if there are actual issues with PPC/PPC64 support, feel free to open detailed tickets.
