### ISSUE TITLE
Support for FreeBSD (patches available)

### ISSUE THREAD

**Issue by iotamudelta** [flang-compiler/flang#131]
Hi,

I've added the patches I created to compile flang on FreeBSD amd64 in [my fork](https://github.com/flang-compiler/flang/compare/master...iotamudelta:master) .

Is there a chance of getting them upstream? If so, what rules should I consider?

Thanks!

**Comment by yurivict** [comment]
Why don't you create a pull request?

**Comment by iotamudelta** [comment]
I'd like to know first if that endeavor has any chance at success / if there are contribution guidelines. :-)

**Comment by sscalpone** [comment]
We’re looking forward to collaborating with those who are interesting in helping. We are still working on our contribution guidelines. I don't have an estimate for when we'll be able to accept contributions other than to say we are actively working on this issue.

**Comment by iotamudelta** [comment]
I take this to mean that my best bet is to maintain the FreeBSD patches out of tree for the time being?

**Comment by sscalpone** [comment]
Yes.  Sorry for the complexity while we get this project rolling.

**Comment by iotamudelta** [comment]
Closing this now in light of off-line discussions w/ @ibara where we decided to merge our patches. It'd be great if @sscalpone could engage with us over at #373 :-) Thanks!
