### ISSUE TITLE
Variable repeat factor / Variable Format Expressions

### ISSUE THREAD

**Issue by GHNewbiee** [flang-compiler/flang#1312]
Does `flang` support **Variable repeat factor** / **Variable Format Expressions**?

Example
```fortran
write(*, '(1x, <neg>i3, <zero>('@',i1), <pos>i2)')
```
where
`neg`, `zero` and `pos` are variables (natural non-zero numbers).

 *Tia*

**Comment by bryanpkc** [comment]
@GHNewbiee AFAIK, the open-source Classic Flang doesn't support variable format expressions. Some commercial compilers based on Classic Flang may have some level of support. For example, Huawei's BiSheng Compiler supports using variable format expressions in `FORMAT` statements, but variable repeat factors are not supported. The format expression in your example produces a compile-time error when I tried it with our downstream compiler, but this works:
```fortran
       WRITE(*, 100) num
100    FORMAT(I<width>)
```
