### ISSUE TITLE
About LLVM 15 release date

### ISSUE THREAD

**Issue by libin049** [flang-compiler/flang#1320]
I saw some issues about [llvm 15], and there exists the release_15x branch on [classic-flang-llvm-project](https://github.com/flang-compiler/classic-flang-llvm-project).  Is there any plans for llvm 15? such as release time , etc.

**Comment by bryanpkc** [comment]
The [flang-15.0.3-20221103](https://github.com/flang-compiler/classic-flang-llvm-project/releases/tag/flang-15.0.3-20221103) tag from classic-flang-llvm-project and the [flang_20221103](https://github.com/flang-compiler/flang/releases/tag/flang_20221103) from flang will work together.
