### ISSUE TITLE
error: Could not parse F file 

### ISSUE THREAD

**Issue by cosminbasca** [flang-compiler/flang#1339]
Hi! 

Great work on getting flang in the llvm ecosystem! I am trying to use it to compile scipy (1.8.1 or newer) with flang instead of gfortran but stumbled upon this error when dealing with PROPACK:

error: Could not parse path/to/scipy-1.8.1/scipy/sparse/linalg/_propack/PROPACK/single/smgs.risc.F

adding -E runs the preprocessor but sadly the resulting fortran code gives a similar error when I try to compile it. 
My fortran is very very rusty :) and I am not sure if there is a way to work around this. Any help much appreciated! 

Cheers,
Cosmin

**Comment by bryanpkc** [comment]
This issue tracker is for the Classic Flang frontend. Are you using Classic Flang or LLVM Flang? For the latter, please post your question to the following issue tracker:

https://github.com/llvm/llvm-project/issues?q=is%3Aissue+is%3Aopen+label%3Aflang%3Afrontend+

**Comment by cosminbasca** [comment]
:+1: thank you
