### ISSUE TITLE
Is it possible to use something like -fno-vectorize -fno-slp-vectorize -fno-unroll-loops in flang?

### ISSUE THREAD

**Issue by zzhang77** [flang-compiler/flang#1347]
I am currently testing a pass which needs to run before vectorization and loop unrolling.  

In clang, it can be done by 
`clang -O3 -S test.c -fno-unroll-loops -fno-vectorize -fno-slp-vectorize`  
After that, the pass can be successfully implemented using opt tool.  

When it applies to Fortran, is there any way to disable these passes during O3 (or O1)?  

Thanks :)

**Comment by bryanpkc** [comment]
`-fno-unroll-loops`, `-fno-vectorize`, and `-fno-slp-vectorize` should also work with `flang`. You can confirm by running `flang` with `-v` and observing the options passed to `clang-15 -cc1`.
