### ISSUE TITLE
Error while build classic flang with llvm 16.04

### ISSUE THREAD

**Issue by edisonchan** [flang-compiler/flang#1412]
OS: Ubuntu 22.04
gcc/g++ 13.1 (installed in /home/edison/gcc13)
llvm 16.04 (use the build-llvm-project.sh that come with llvm, just change the INSTALL_PREFIX= to "/home/edison/llvm").

and then run build-flang.sh that come with flang( the INSTALL_PREFIX= was set to "/home/edison/llvm").
```
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /home/edison/llvm/bin/clang++
-- Check for working CXX compiler: /home/edison/llvm/bin/clang++ - broken
CMake Error at /home/edison/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:60 (message):
  The C++ compiler

    "/home/edison/llvm/bin/clang++"

  is not able to compile a simple test program.

```

The clang++ is need to add "--gcc-toolchain=/home/edison/gcc13" to build program in my system(I don't know why),  I think this might be the cause of the problem.

But I'm not very familiar with cmake, does not know how to pass --gcc-toolchain to cmake.

**Comment by bryanpkc** [comment]
@edisonchan Did you try installing the `build-essential` package on Ubuntu? That should install GCC and other tools in system locations, so that `clang++` can build programs without `--gcc-toolchain=`.

**Comment by edisonchan** [comment]
> @edisonchan Did you try installing the `build-essential` package on Ubuntu? That should install GCC and other tools in system locations, so that `clang++` can build programs without `--gcc-toolchain=`.

Thanks for your replay, it works ~
