### ISSUE TITLE
SPEC2017 521_r run error

### ISSUE THREAD

**Issue by edisonchan** [flang-compiler/flang#1413]
OS: ubuntu 22.04
https://github.com/flang-compiler/classic-flang-llvm-project: built with enable "clang;opengmp;mlir;" and installed to /home/edison/llvm
flang: installed to /home/edison/llvm

```
/home/edison/llvm/bin/clang		-std=c99
/home/edison/llvm/bin/clang++  	-std=c++03
/home/edison/llvm/bin/flang

COPTIMIZE	            = -Ofast -march=x86-64 -mtune=core-avx2 -mfma  -mavx -mavx2  -fomit-frame-pointer -fno-strict-aliasing -fno-finite-math-only
CXXOPTIMIZE	            = -Ofast -march=x86-64 -mtune=core-avx2 -mfma  -mavx -mavx2  -fomit-frame-pointer -fno-strict-aliasing -fno-finite-math-only
FOPTIMIZE	            = -Ofast -march=x86-64 -mtune=core-avx2 -mfma  -mavx -mavx2  -fomit-frame-pointer -fno-strict-aliasing -Kieee  # -Kieee is need for 549.fotonik3d_r with flang

EXTRA_CFLAGS            = -Wno-implicit-int

LIBS                    = -L/home/edison/llvm/lib -lflang

PORTABILITY	= -DSPEC_LP64

521.wrf_r,621.wrf_s:  #lang='F,C'
   CPORTABILITY	= -DSPEC_CASE_FLAG
   FPORTABILITY	= -Mbyteswapio	#for flang

```

It's OK for build 521 but error while run:

```
****************************************
Contents of wrf.err
****************************************
Error during math dispatch processing...
__pgmath_abort:Math dispatch table is either misconfigured or corrupted.
****************************************
```

-O3 have same problem.

**Comment by bryanpkc** [comment]
@shivaramaarao Would you have time to take a look?

**Comment by shivaramaarao** [comment]
could you please share the hardware details of the machine used for running the benchmark?. Does the error come only for wrf or other benchmarks as well?

**Comment by edisonchan** [comment]
CPU: Intel Core-i9 13900K
Memory: DDR5-6400 16GB*2
Mainboard: ROG STRIX Z790-H GAMING WIFI, BIOS 0904 03/29/2023
BIOS: All Default(press F5 to set default optimization)

Yes, the error come only for wrf, I have try all other sub-test of SPEC2017.

**Comment by d-parks** [comment]
Running with environment variable MTH_I_DEBUG=1 will show you what the runtime library has detected as the processor class you are running on.

**Comment by edisonchan** [comment]
> Running with environment variable MTH_I_DEBUG=1 will show you what the runtime library has detected as the processor class you are running on.

I dont know how to get the info after set MTH_I_DEBUG=1.


```
./wrf_r_base.llvm_16-m64
--- WARNING: traj_opt is zero, but num_traj is not zero; setting num_traj to zero.
--- NOTE: sst_update is 0, setting io_form_auxinput4 = 0 and auxinput4_interval = 0 for all domains
--- NOTE: grid_fdda is 0 for domain      1, setting gfdda interval and ending time to 0 for that domain.
--- NOTE: both grid_sfdda and pxlsm_soil_nudge are 0 for domain      1, setting sgfdda interval and ending time to 0 for that domain.
--- NOTE: obs_nudge_opt is 0 for domain      1, setting obs nudging interval and ending time to 0 for that domain.
bl_pbl_physics /= 4, implies mfshconv must be 0, resetting
--- NOTE: num_soil_layers has been set to      4
WRF V3.6.1 MODEL
 *************************************
 Parent domain
 ids,ide,jds,jde             1           74            1           61
 ims,ime,jms,jme            -4           79           -4           66
 ips,ipe,jps,jpe             1           74            1           61
 *************************************
DYNAMICS OPTION: Eulerian Mass Coordinate
   alloc_space_field: domain             1 ,                 128355772  bytes allocated
  med_initialdata_input: calling input_input
   Resetting the hypsometric_opt from default value of 2 to 1
Timing for processing wrfinput file (stream 0) for domain        1:    0.00510 elapsed seconds
INPUT LandUse = "USGS"
 LANDUSE TYPE = "USGS" FOUND           33  CATEGORIES            2  SEASONS WATER CATEGORY =            16  SNOW CATEGORY =            24
INITIALIZE THREE Noah LSM RELATED TABLES
 LANDUSE TYPE = USGS FOUND           27  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND           19  CATEGORIES
Error during math dispatch processing...
__pgmath_abort:Math dispatch table is either misconfigured or corrupted.
```

**Comment by edisonchan** [comment]
When use the last release flang (https://github.com/flang-compiler/flang/releases/download/flang_20190329/flang-20190329-x86-70.tgz) to build 521.wrf_r, the test is OK here.

**Comment by shivaramaarao** [comment]
just before the wrf run command, can you please set the following environment variables?
export MTH_I_DEBUG=1
export MTH_I_STATS=1

setting above environment variables will result in a dump of math function mapping table and information about intrinsic call that is not mapped to runtime function call. please share the dump.

**Comment by shivaramaarao** [comment]
Is the issue specific to intel 13900k?. I could not reproduce the issue on other systems. could you please confirm?

**Comment by edisonchan** [comment]
> Is the issue specific to intel 13900k?. I could not reproduce the issue on other available systems. could you please confirm?

It's not just 13900K only, my AMD 5800X also have such problem. The attach file is the error log.
 
[wrf.txt](https://github.com/flang-compiler/flang/files/12332032/wrf.txt)

My Install step of LLVM and Flang: 

0: I have a gcc13(gcc, g++, gfortran) install to /home/edison/gcc13

1. mkdir ~/Downloads/llvm_source
2. cd ~/Downloads/llvm_source/
3. git clone https://github.com/flang-compiler/classic-flang-llvm-project.git
4. modify the build-llvm-project.sh file:
```
INSTALL_PREFIX="/home/edison/llvm"
GCC_INSTALL_PREFIX="/home/edison/gcc13"
```
```
CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
    -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
    -DCMAKE_C_COMPILER=$C_COMPILER_PATH \
    -DCMAKE_CXX_COMPILER=$CXX_COMPILER_PATH \
    -DGCC_INSTALL_PREFIX=$GCC_INSTALL_PREFIX \ 
    -DLLVM_TARGETS_TO_BUILD=$TARGET \
    -DLLVM_ENABLE_CLASSIC_FLANG=ON \
    -DFLANG_BUILD_NEW_DRIVER=OFF"
```
5. cd classic-flang-llvm-project , then run: bash build-llvm-project.sh -n 8 -i 1
6. check clang: 
clang -v
```
clang version 16.0.4 (https://github.com/flang-compiler/classic-flang-llvm-project.git 5c04f282bab1b2e24c3eccab15fe9ff6be7c8f62)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/edison/llvm/bin
Found candidate GCC installation: /home/edison/gcc13/lib/gcc/x86_64-pc-linux-gnu/13.1.0
Selected GCC installation: /home/edison/gcc13/lib/gcc/x86_64-pc-linux-gnu/13.1.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```
 7. cd ~/Downloads/llvm_source, run: git clone https://github.com/flang-compiler/flang.git
 8. modify the build-flang.sh:
```
INSTALL_PREFIX="/home/edison/llvm"
```
9. cd flang, and then run: bash build-flang.sh -n 8
10. check flang: flang -v
```
flang version 16.0.4 (https://github.com/flang-compiler/classic-flang-llvm-project.git 5c04f282bab1b2e24c3eccab15fe9ff6be7c8f62)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/edison/llvm/bin
Found candidate GCC installation: /home/edison/gcc13/lib/gcc/x86_64-pc-linux-gnu/13.1.0
Selected GCC installation: /home/edison/gcc13/lib/gcc/x86_64-pc-linux-gnu/13.1.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```
11. build 521_r:
[llvm.cfg.txt](https://github.com/flang-compiler/flang/files/12332140/llvm.cfg.txt)

cd ~/cpu2017
. ./shrc
runcpu -c llvm.cfg -a setup 521
runcpu -c llvm --noreportable -n 1 521

**Comment by shivaramaarao** [comment]
Hi, Thanks. I could reproduce the issue. It looks like compiler is generating a vector library call that is not supported in the libpgmath.

you can try following patch to resolve the issue as a workaround until the issue gets resolved.

git diff ./include/llvm/Analysis/VecFuncs.def
diff --git a/llvm/include/llvm/Analysis/VecFuncs.def b/llvm/include/llvm/Analysis/VecFuncs.def
index 6491fdaf5633..fdc028d69d69 100644
--- a/llvm/include/llvm/Analysis/VecFuncs.def
+++ b/llvm/include/llvm/Analysis/VecFuncs.def
@@ -1154,7 +1154,7 @@ TLI_DEFINE_VECFUNC("__rs_log10_1", "__rs_log10_16", FIXED(16))

 TLI_DEFINE_VECFUNC("__fd_log_1", "__fd_log_2", FIXED(2))
 TLI_DEFINE_VECFUNC("__fd_log_1", "__fd_log_4", FIXED(4))
-TLI_DEFINE_VECFUNC("__fd_log_1", "__fd_log_8", FIXED(8))
+// TLI_DEFINE_VECFUNC("__fd_log_1", "__fd_log_8", FIXED(8))

 TLI_DEFINE_VECFUNC("__fs_log_1", "__fs_log_4", FIXED(4))
 TLI_DEFINE_VECFUNC("__fs_log_1", "__fs_log_8", FIXED(8))
@@ -1162,7 +1162,7 @@ TLI_DEFINE_VECFUNC("__fs_log_1", "__fs_log_16", FIXED(16))

 TLI_DEFINE_VECFUNC("__pd_log_1", "__pd_log_2", FIXED(2))
 TLI_DEFINE_VECFUNC("__pd_log_1", "__pd_log_4", FIXED(4))
-TLI_DEFINE_VECFUNC("__pd_log_1", "__pd_log_8", FIXED(8))
+// TLI_DEFINE_VECFUNC("__pd_log_1", "__pd_log_8", FIXED(8))

 TLI_DEFINE_VECFUNC("__ps_log_1", "__ps_log_4", FIXED(4))
 TLI_DEFINE_VECFUNC("__ps_log_1", "__ps_log_8", FIXED(8))

**Comment by bryanpkc** [comment]
@shivaramaarao Could you create a PR in classic-flang-llvm-project with this fix?
