### ISSUE TITLE
[regression] An ICE while building libmbd after PR #1422

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#1442]
After introduction of #1422 the libmbd library (see https://github.com/libmbd/libmbd.git ) cannot be built. An Internal Compiler Error (ICE) can be observed when trying to compile the mbd_methods.F90 file (https://github.com/libmbd/libmbd/blob/master/src/mbd_methods.F90 ).
```
[ 60%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_methods.F90.o
cd src && flang -Dmbd_EXPORTS -Isrc -g -fPIC -c src/mbd_methods.F90 -o CMakeFiles/mbd.dir/mbd_methods.F90.o
Lowering Error: symbol freq$sd is an inconsistent array descriptor
Lowering Error: symbol freq$sd is an inconsistent array descriptor
F90-F-0000-Internal compiler error. Errors in Lowering       2  (src/mbd_methods.F90: 154)
F90/aarch64 Linux F90  - 1.5 2017-05-01: compilation aborted
```

**Comment by bryanpkc** [comment]
@wanbinchen-hnc Could you help take a look at this?

**Comment by wanbinchen-hnc** [comment]
@pawosm-arm @bryanpkc A fixing PR has been submitted.

**Comment by pawosm-arm** [comment]
The fix has worked for me.
