### ISSUE TITLE
Question: Where are the prebuilt binaries of Flang on Windows ?

### ISSUE THREAD

**Issue by Ranne314** [flang-compiler/flang#1461]
I am trying to install Flang on Windows, I already have Clang installed, How to download prebuilt binaries of Flang on Windows ????

**Comment by Ranne314** [comment]
Answer if you are a Skibidi Toilet Sigma Rizzler 🗣️🗣️🗣️🗣️🗣️🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by Ranne314** [comment]
Plz answer, I really need it

**Comment by bryanpkc** [comment]
We current don't offer prebuilt Windows binaries of Classic Flang for download. [There may be Windows builds of the new LLVM Flang compiler](https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0), but this is not the issue tracker for LLVM Flang.
