### ISSUE TITLE
Segfault with derived type in OpenMP firstprivate clause

### ISSUE THREAD

**Issue by janusw** [flang-compiler/flang#158]
Please consider the following test case:

```
program p

  type t1
    integer, allocatable :: a(:,:)
  end type

  type t2
    type(t1) :: b
  end type

  type(t2) :: x

  print *, "*"
!$omp parallel firstprivate(x)
  print *, "**"
!$omp end parallel
  print *, "***"
end
```

After compiling this with `flang -mp` and running the generated program, I get:
```
 *
 **
Segmentation fault (core dumped)
```

Note that PGI 17.4 also produces a segfault, but slightly earlier:
```
 *
Segmentation fault (core dumped)
```

gfortran 4.8 rejects it with:
```
!$omp parallel firstprivate(x)
                              1
Error: FIRSTPRIVATE clause object 'x' has ALLOCATABLE components at (1)
```
but 4.9 and above compile it well and give the expected runtime output. I think it's valid since OpenMP 4.0.

Cheers,
Janus

**Comment by janusw** [comment]
In fact the behavior of flang and pgfortran seems to be identical after all (but a bit random): Both print the one-star line and a varying number of two star lines (I observed 0-4 on a six-core machine) before the segfault.

**Comment by janusw** [comment]
I also reported this bug in the PGI Forums:

http://www.pgroup.com/userforum/viewtopic.php?t=5664

**Comment by janusw** [comment]
The problem seems to be related to the deallocation of the allocatable components, since the backtrace for the segfault looks like this:
```
(gdb) bt
#0  0x00007ffff7a2e6f0 in __fort_dealloc03 () from /usr/local/lib/libflang.so
#1  0x00007ffff7a2e5bc in f90_dealloc03 () from /usr/local/lib/libflang.so
#2  0x00007ffff7a2e8c7 in f90_dealloc_mbr03 () from /usr/local/lib/libflang.so
```

When setting `OMP_NUM_THREADS=1` the segfault still occurs (sporadically).

**Comment by janusw** [comment]
It seems like the bug is gone on curren trunk (f7af78c). I'd guess that it has been fixed by e3200a1.

@mleair: Can you confirm that?

Thanks,
Janus

**Comment by mleair** [comment]
Yes, that is the change that fixed your issue (I confirmed it in our internal bug tracking system).

**Comment by janusw** [comment]
Great, thanks for the confirmation (and for the fix, of course!).
