### ISSUE TITLE
Why do transpose routines have an ifdef for TARGET_X8664?

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/flang#161]
runtime/flang/transpose_cmplx16.F95
runtime/flang/transpose_cmplx8.F95
runtime/flang/transpose_real4.F95
runtime/flang/transpose_real8.F95

E.g.

subroutine ftn_transpose_real8( a, lda, alpha, buffer, bufrows, bufcols )
  implicit none
#ifdef TARGET_X8664
  integer*8 lda
#else
  integer lda
#endif

**Comment by pawosm-arm** [comment]
Do they really? The "Fix the ifdefs in fortran runtime for 64 bit descriptors" commit seems to remove them ifdefs.

**Comment by sscalpone** [comment]
Woo hoo!
