### ISSUE TITLE
OpenMP reduction clause with array on the stack happens to "Illegal instruction" error

### ISSUE THREAD

**Issue by yhirokawa** [flang-compiler/flang#176]
Dear all developers,

I'm testing a my developing real-scientific simulation code with OpenMP enabled flang.
Unfortunately, "Illegal instruction" error happens OpenMP reduction clause of array on the stack.
For the heap allocated array, reduction clause works fine.
ifort and gfortran work fine for both cases. I think this is a bug of flang.

Could you please check the following test codes?

```Fortran
program main
  implicit none
  integer,parameter :: n = 2
  call reduction_test(n)

contains
  subroutine reduction_test(n)
    implicit none
    integer, intent(in) :: n
    real(8) :: arr(n)
    integer :: i

    arr=0.d0
!$omp parallel do reduction(+:arr)
    do i=1,n
      arr(i) = arr(i) + i
    end do
!$omp end parallel do

    print *, arr(n)
  end subroutine
end program
```

```
$ llvm-config  --version
3.9.1
$ flang --version
clang version 3.9.1 (https://github.com/flang-compiler/clang.git 600c2759c7d9fe9e1c3321bedbb701403f907142) (https://github.com/llvm-mirror/llvm.git a093ef43dd592b729da46db4ff3057fef9a46023)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/yhirokawa/packagellvm-flang/3.9.1/bin
$ flang -mp -O3 -o xtest test.f90
$ ./xtest
Illegal instruction
$ gfortran -fopenmp -O3 -o xtest test.f90
$ ./xtest
   2.0000000000000000
```

**Comment by mleair** [comment]
A fix for this issue has been committed.

**Comment by yhirokawa** [comment]
Thank you so much! I tested latest flang (3dfad47999fbf4d27a1fe59678d65d427d223ce6) with LLVM 4.0.1, it worked fine.

    $ flang --version
    clang version 4.0.1 (https://github.com/flang-compiler/clang.git 79d19704b305adb0da2c9f088b4a21e6c5fa6c75) (https://github.com/llvm-mirror/llvm.git c8fccc53ed66d505898f8850bcc690c977a7c9a7)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /home/yhirokawa/package/llvm-flang/4.0.1/bin
    $ flang -mp -O3 -o xtest test.f90
    $ ./xtest
        2.000000000000000
