### ISSUE TITLE
Real128 support 

### ISSUE THREAD

**Issue by ewinnington** [flang-compiler/flang#177]
Please support Real128 (quad precision)

```
real(16) x

x = 1.q0

```

A software implementation is preferable (even in the case it is slow) instead of a real(10) truncation. 

We dip into real(16) for high precision parts of our computation (stochastic dynamic programming applied to optimizing the operation of hydropower plants) that are outside the critical performance loops.

**Comment by bryanpkc** [comment]
Patch 1 in a series is now up for review: #1125
