### ISSUE TITLE
-fbackslash seems to always be in effect, regardless of command-line

### ISSUE THREAD

**Issue by rolk** [flang-compiler/flang#179]
Consider this minimal example:

    program minex
    print *, 'C:\notes'
    end program minex

Regardless of whether it is compiled with `flang minex.f90`, `flang -fno-backslash minex.f90` or `flang -fbackslash minex.f90`, it always interpret the `\n` sequence as a newline in the output. The same goes for `-Mbackslash`.

And BTW, the documentation of `-fbackslash`/`-fno-backslash` (as printed with `flang --help`) doesn't make any sense: it is the same string for both.

Fortran front-end version 460ef03, clang backend version edf56fd, llvm version a093ef4. Platform: Ubuntu 16.04.

**Comment by sscalpone** [comment]
For me, -Mbackslash and -fno-backslash are producing output without the newline.

```
+ flang minex.f90
+ a.out
 C:
otes

+ flang -Mbackslash minex.f90
+ a.out
 C:\notes

+ flang -Mnobackslash minex.f90
+ a.out
 C:
otes

+ flang -fbackslash minex.f90
+ a.out
 C:
otes

+ flang -fno-backslash minex.f90
+ a.out
 C:\notes
```

Part of the confusion for me is that -Mbackslash and -fno-backslash mean the same thing.  For gfortran, -backslash tells the compiler to use C-style rules for backslash.  For PGI, -Mbackslash means treat backslash like a regular character.

I'm using clang/flang/llvm release_40 as of 8/8/2017.

We're updating the 'help' commands generally to clarify the meaning of the 'no' options.

**Comment by rolk** [comment]
> For me, -Mbackslash and -fno-backslash are producing output without the newline.
> I'm using clang/flang/llvm release_40 as of 8/8/2017.

Hm. That's strange. I still got the problem (all combinations output \n as newline) with:

    $ flang --version
    clang version 4.0.1 (https://github.com/flang-compiler/clang.git e539cad092cc5b68086582e3c9365c6ccd45a0f2) (https://github.com/llvm-mirror/llvm.git c8fccc53ed66d505898f8850bcc690c977a7c9a7)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix    
    InstalledDir: /usr/local/bin

    $ git log -1 --pretty=format:'%h'
    0f21770

But how can this be build-dependent O.o?

> We're updating the 'help' commands generally to clarify the meaning of the 'no' options.
Yes, right now it seems that the option without `no-` prefix is correct, but the no-version is also explicitly listed, with the same text:

    $ flang -help | grep backslash
      -fbackslash             Treat backslash as C-style escape character
      -fno-backslash          Treat backslash as C-style escape character
      -Mbackslash             Treat backslash like any other character in character strings
      -Mnobackslash           Treat backslash like any other character in character strings

**Comment by rolk** [comment]
I don't know exactly when it happened, because I don't rebuild more than ever so often, but as of commit fd99090, this problem is now gone anyway.
