### ISSUE TITLE
Long-term plan for the project

### ISSUE THREAD

**Issue by aprokop** [flang-compiler/flang#204]
What's the long term goal of the project? Is it to become a part of llvm eco-system, or to be standalone? Are there efforts to at least push clang changes upstream? Is it to be maintained by a company (Nvidia?), or by a community?

One of the reasons for my asking is that I'd like to add flang to [spack package manager](github.com/llnl/spack). If there are plans to merge it with upstream in some form, it may be worthwhile to wait till that happens.

**Comment by ChinouneMehdi** [comment]
see <http://lists.flang-compiler.org/pipermail/flang-announce_lists.flang-compiler.org/2017-August/000001.html>

**Comment by aprokop** [comment]
@ChinouneMehdi Thank you! That was quite helpful.
