### ISSUE TITLE
fails to build flang.

### ISSUE THREAD

**Issue by ChinouneMehdi** [flang-compiler/flang#205]
i succeeded to build llvm,openm-llvm,clang,flang before, but recently i failed to build flang in the same way.
all those errors(>20) are in errmsgdf.h file in lines : 1013,1022,1026,1030,1034 ...
`error: expected identifier = 0,` ..etc

**Comment by ppenzin-nv** [comment]
Can you please provide more output from the build? What compiler are you using?

**Comment by ChinouneMehdi** [comment]
It was my fault, some files have windows line-endings after i fixed them everything goes well.
