### ISSUE TITLE
ICE in flang1 when there are two consecutive WHERE statements operating on the same data

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#206]
Consider simple Fortran code:
```
subroutine sub1(valA, valB, val1, sth)

  implicit none

  real :: valA, valB
  real, pointer :: val1(:)
  real, pointer :: sth(:)

  where (val1(:) < 0.5) sth(:) = valA
  where (val1(:) >= 0.5) sth(:) = valB
end subroutine sub1
```
This code, when compiled at optimization level 2 and higher (including -Os and -Ofast) causes ICE in flang1's comm_optimize_pre(void) function at call to fuse_forall(0);:

```
F90-S-0000-Internal compiler error. remove_stmt: corrupt STD or deleting statement twice      12 (where.f90: 13)
  0 inform,   0 warnings,   1 severes, 0 fatal for sub1
```

This failure can be prevented by adding -Hx,47,0x02 at flang's command line, or by applying following patch:
```
diff --git a/tools/flang1/flang1exe/commopt.c b/tools/flang1/flang1exe/commopt.c
index c5f087c..a342a3a 100644
--- a/tools/flang1/flang1exe/commopt.c
+++ b/tools/flang1/flang1exe/commopt.c
@@ -208,7 +208,6 @@ comm_optimize_pre(void)
   }
 #endif
   selection_sort();
-  fuse_forall(0);
   comm_optimize_end();
 }
```

**Comment by pawosm-arm** [comment]
I tried to follow the 'deleting statement twice' lead and I found that questioned statement is indeed attempted to be deleted twice: first time by wrilts() function:
```
    STD_NEXT(rw_state.std_before) = rw_state.std_after;
    STD_PREV(rw_state.std_after) = rw_state.std_before;
```
...second time by remove_stmt() function (where the error message is also printed):
```
  if (STD_NEXT(prev) != std || STD_PREV(next) != std) {
    interr("remove_stmt: corrupt STD or deleting statement twice", std,
           ERR_Severe);
    return;
  }
  STD_NEXT(prev) = next;
  STD_PREV(next) = prev;
```
The rdilts()/wrilts() pair is called from forall_dependency() function, relies on side effect heavily and for some reason it effectively deletes statement that was just added to the list:

This is how it's added:

```
      newstd = add_stmt_before(newforall, std);
      STD_PAR(newstd) = par;
      STD_TASK(newstd) = task;

      /* add the newstd to the std fuse list */
      replace_loop_on_fuse_list(std, newstd);

```
This is how it's deleted (with -O2 or higher) few lines later (when newfg is non-zero):
```
     /* need to add this to flow graph otherwise add_loop_hd will drop it */
      if (flg.opt >= 2 && !XBIT(2, 0x400000)) {
        int fg;
        int newfg;
        fg = STD_FG(std);
        newfg = add_fg(FG_LPREV(fg));
        if (newfg) {
          rdilts(newfg);
          FG_STDLAST(newfg) = newstd;
          FG_STDFIRST(newfg) = newstd;
          wrilts(newfg);
        }
      }

```
It may not be clear from quoted code, due to heavy use of side effect, but wrilts() function operates on two statements: before and after the one just added earlier by add_stmt_before() function, effectively removing it from the list.

**Comment by gklimowicz** [comment]
I can't reproduce this with the current Flang compiler. Please reopen if you have another reproducer showing this problem.

```$ flang -c -Os -Ofast sub1.f90```

produced no error message.
