### ISSUE TITLE
compile errors on aarch64

### ISSUE THREAD

**Issue by trentdhooge** [flang-compiler/flang#207]
Built llvm from https://github.com/llvm-mirror/llvm.git branch release_40. clang from https://github.com/flang-compiler/clang.git branch flang_release_40 and openmp-llvm from https://github.com/llvm-mirror/openmp.git branch release_40 . All three built on aarch64, ppc64le and x86_64.

cloned https://github.com/flang-compiler/flang.git and using the built software , ppc64le and x86_64 flang built fine, but aarch64 has some errors.

 cmake line from the rpm spec file

cmake -DCMAKE_INSTALL_PREFIX=%{pkgdir} -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_Fortran_COMPILER=flang -DFLANG_LIBOMP=/opt/openmp-llvm/4.0/lib/libomp.so ../%{pkgname}

+ make
Scanning dependencies of target flangADT
[  0%] Building C object lib/ADT/CMakeFiles/flangADT.dir/hash.c.o
[  0%] Linking C static library ../libflangADT.a
[  0%] Built target flangADT
Scanning dependencies of target flangArgParser
[  0%] Building C object lib/ArgParser/CMakeFiles/flangArgParser.dir/arg_parser.c.o
[  1%] Building C object lib/ArgParser/CMakeFiles/flangArgParser.dir/debug_action.c.o
[  1%] Building C object lib/ArgParser/CMakeFiles/flangArgParser.dir/xflag.c.o
[  1%] Linking C static library ../libflangArgParser.a
[  1%] Built target flangArgParser
Scanning dependencies of target scutil
[  1%] Building C object lib/scutil/CMakeFiles/scutil.dir/default-fperror.c.o
[  1%] Building C object lib/scutil/CMakeFiles/scutil.dir/host-fp-folding.c.o
[  1%] Building C object lib/scutil/CMakeFiles/scutil.dir/int128.c.o
[  1%] Building C object lib/scutil/CMakeFiles/scutil.dir/legacy-folding-api.c.o
/home/tdhooge/rpmbuild/BUILD/flang-1.5/flang/lib/scutil/legacy-folding-api.c:1954:10: error: passing 'uint32_t *' (aka 'unsigned int *') to parameter of type 'int32_t *' (aka 'int *')
      converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
  wrap_l(u, &x);
         ^
/home/tdhooge/rpmbuild/BUILD/flang-1.5/flang/lib/scutil/legacy-folding-api.c:81:14: note: passing argument to parameter 'res' here
wrap_l(INT64 res, int64_t *x)
             ^
/home/tdhooge/rpmbuild/BUILD/flang-1.5/flang/lib/scutil/legacy-folding-api.c:1954:13: error: passing 'uint64_t *' (aka 'unsigned long *') to parameter of type 'int64_t *' (aka 'long *')
      converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
  wrap_l(u, &x);
            ^~
/home/tdhooge/rpmbuild/BUILD/flang-1.5/flang/lib/scutil/legacy-folding-api.c:81:28: note: passing argument to parameter 'x' here
wrap_l(INT64 res, int64_t *x)
                           ^
2 errors generated.
make[2]: *** [lib/scutil/CMakeFiles/scutil.dir/build.make:135: lib/scutil/CMakeFiles/scutil.dir/legacy-folding-api.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:220: lib/scutil/CMakeFiles/scutil.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.5QiF1L (%install)

**Comment by pawosm-arm** [comment]
```
sed -i -e 's/-Werror/-Wall/g' flang/CMakeLists.txt
```
should help.
Start cmake again so it could process changed CMakeLists.txt file.

**Comment by trentdhooge** [comment]
That works, and at least works around the issue. Thanks.
