### ISSUE TITLE
LLVM 5 support

### ISSUE THREAD

**Issue by janusw** [flang-compiler/flang#215]
Now that LLVM 5 is final (http://lists.llvm.org/pipermail/llvm-dev/2017-September/117136.html), I'd like to know what the status of flang is with respect to that release. The README still says "The latest supported LLVM version is 4.0", but I see that there is a branch of the modified clang already (https://github.com/flang-compiler/clang/tree/flang_release_50).

Does the current flang master fully work with LLVM 5, or should one expect any problems?

Cheers,
Janus

**Comment by sscalpone** [comment]
The flang master works with LLVM 5.  The readme needs to be updated.  We're investigating this llvm commit -- 52ebe03cb0a728134e66d04f85281bc5a60d7091 -- to see if it or flang is causing some incorrect test results when run with the PGI+LLVM compiler.

**Comment by janusw** [comment]
Thanks for the feedback! Indeed I was able to build flang based on LLVM5, and "make check-flang" shows 14 expected passes, no failures.

**Comment by janusw** [comment]
Would you mind updating README.md accordingly?

Thanks,
Janus

**Comment by sscalpone** [comment]
Sure.  I just submitted an update to the README.md that should work it way to github by Tuesday.

**Comment by janusw** [comment]
Ah, great. Thank you!

(Btw, I fixed another small typo in the README some time ago, see #142. This is actually the leftover of a larger patch, where the other issues had been fixed in the meantime. Not a big deal, but would be nice if you could fix this on your master as well at some point).
