### ISSUE TITLE
tools/flang1/utils/ast/ast.n and tools/flang1/docs/ast.n is the same file

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#225]
I've noticed that tools/flang1/utils/ast/ast.n and tools/flang1/docs/ast.n is the same file. And it's not a symlink. Any changes in one place should be performed in the other. This poses maintenance nightmare. I guess one of them may be dropped.

**Comment by sscalpone** [comment]
Yup.  There are other examples.  We have some re-factoring to do.  I suppose the shared files ought to be in a common directory and referenced relatively.

**Comment by pawosm-arm** [comment]
tools/flang1/docs/ast.n has gone, closing it.
