### ISSUE TITLE
CMake mis-identifies flang

### ISSUE THREAD

**Issue by nncarlson** [flang-compiler/flang#236]
At the moment CMake 3.9.1 identifies flang as "GNU" (back in June it was "PGI").  Is this due to a lack of discernment by CMake, or is flang defining preprocessor macros that make it masquerade as GNU?

**Comment by nncarlson** [comment]
I've since located the commit that fixed the "PGI" issue (75c13fd), and discovered that `__FFLANG`, `__FLANG_MAJOR__`, `__FLANG_MINOR__`, and `__FLANG_PATCHLEVEL__` are all defined now.  The misidentification is pretty clearly a CMake problem.

**Comment by janusw** [comment]
Note that flang is correctly identified by cmake 3.10.
