### ISSUE TITLE
Generated code error with empty C binding name

### ISSUE THREAD

**Issue by nncarlson** [flang-compiler/flang#237]
The current flang (5.0) generates bad intermediate code from this valid code example
```fortran
module example
contains
  integer function foo() bind(c,name='')
  end function
end module
```
Here's the output
```
$ flang -c flang-bug-20170923a.f90 
/tmp/flang-bug-20170923a-823831.ll:8:20: error: expected function name
define signext i32 @() !dbg !16 {
                   ^
1 error generated.
```
Flang apparently isn't happy with an empty binding name.  But that is legal (and used to prevent the creation of a global symbol); see 15.4.1 of the 2003 standard.

**Comment by nncarlson** [comment]
This issue is related to the ECP ExaAM project.

**Comment by sscalpone** [comment]
Not sure this is legal.  From 15.4.1: If a procedure has the BIND attribute with the NAME= specifier and the value of its expression, after discarding leading and trailing blanks, has nonzero length, the procedure has this as its binding label.

Both ifort and gfortran create global symbols for the name.  Intel generates example_mp_foo and gfortran generates __example_MOD_foo.  Without the bind(), gfortran generates the same name but ifort adds a trailing underscore, example_mp_foo_.  Flang gexample_foo_g.enerates.

The external name of a subprogram should no be pre-pended with any sort of module path; the external name should be simply the name provided in the bind attribute.

What does the ExaAM project code expect the empty bind name to do?

**Comment by nncarlson** [comment]
I'm pretty certain this is legal.  You need to read further in that paragraph of 15.4.1, "If a procedure has the BIND attribute with the NAME= specifier and the value of its expression, after discarding leading and trailing blanks, has nonzero length ... **Otherwise, the procedure has no binding label.**"  Same language in F2008 15.5.2.

We get the address of these functions with the C_FUNLOC intrinsic to populate a C structure of callbacks.

**Comment by nncarlson** [comment]
To expand a bit ...   Without the NAME= specifier, the declared procedure name becomes the global symbol with no modification.  That means one needs to be concerned with potential name collisions.  In use cases where the procedure is not intended to be referenced externally by name, it is safest to specify NAME="", which apparently results in a symbol name that is the mangled form of the procedure name typical of module procedures without the BIND attribute (minimal potential for name collisions).

This is obviously trivial to work around, and so not a high priority bug, but it ought to be fixed at some point.

**Comment by sscalpone** [comment]
In any case, the compiler needs to be fixed.  Thanks for the explanation of how the BIND should behave.

**Comment by nncarlson** [comment]
It looks like 6d8ef84 fixed the ICE, however the resulting code is incorrect -- or at least a "poor quality" implementation.  The 2008 standard clearly defines three cases in 15.5.2 par 2:
1. No `NAME=` specifier (binding label is the procedure name)
2. With` NAME=` specifier and *non-empty* name (binding label is name)
3. With `NAME=""` specifier (no binding label)

Flang now treats case 3 the same as case 1, and I think this is inappropriate.  **The point of no binding label is to avoid name collisions.**  In practice it seems impossible to not create a binding label (or object file symbol), so what other compilers do is to create a mangled name.  For my example above, Intel creates the symbol `example_mp_foo_`, GFortran the symbol `__example_MOD_foo`, and NAG the symbol `example_MP_foo`.  These are relatively unlikely to cause a name collision.  But flang creates the symbol `foo`, which is terrible when one is looking for no binding label.

**Comment by nncarlson** [comment]
I've confirmed that a972bbd fixes this.  Thanks!
