### ISSUE TITLE
Rejected structure constructor with CLASS(*) allocatable component

### ISSUE THREAD

**Issue by nncarlson** [flang-compiler/flang#243]
Flang rejects the valid structure constructor `foo(42)` in the following example
```fortran
type foo
  class(*), allocatable :: val
end type
type(foo) :: x
x = foo(42)
end
```
```
$ flang flang-bug-20170924b.f90 
F90-F-0155-Too many elements in structure constructor- type foo (flang-bug-20170924b.f90: 5)
F90/x86-64 Linux Flang - 1.5 2017-05-01: compilation aborted
```
It seems to be an issue with CLASS(*); if it is replaced with INTEGER, the constructor is accepted.

This issue is related to the ECP ExaAM project.

**Comment by nncarlson** [comment]
This bug is still present in 1efaacf

**Comment by nncarlson** [comment]
This example now compiles with 543785e7, however the assignment is not being done correctly. Here's a modified example that checks the result of the assignment:
```fortran
type foo
  class(*), allocatable :: val
end type
type(foo) :: x
x = foo(42)
select type (val => x%val)
type is (integer)
  if (val /= 42) stop 1
class default
  stop 2
end select
end
```
The dynamic type of `x%val` should be integer with value 42, however the program exits at the `stop 2` statement, so apparently the dynamic type is not integer.

**Comment by gklimowicz** [comment]
I've added this test case to the list of things we will dig into, Neil.

**Comment by nncarlson** [comment]
Both examples fixed as of 8/12/2018.
