### ISSUE TITLE
Wrong assignment of structure with CLASS(*) allocatable component

### ISSUE THREAD

**Issue by nncarlson** [flang-compiler/flang#244]
This example compiles cleanly but produces incorrect results
```fortran
type foo
  class(*), allocatable :: val
end type
type(foo) :: x, y
allocate(x%val, source=42)
y = x
print *, allocated(y%val), ' (expect T)'
if (allocated(y%val)) then
  select type (val => y%val)
  type is (integer)
    print *, val, ' (expect 42)'
  class default
    print *, 'not expected type'
  end select
end if
end
```
The output:
```
$ flang flang-bug-20170924c.f90 
$ ./a.out
  T  (expect T)
           0   (expect 42)
```
The assignment `y = x` is properly allocating the `val` component of `y` but it is not assigning it the right value.  If the component is instead declared
```fortran
  integer, allocatable :: val
```
the correct results are obtained.  Flang seems to have some general issues handling CLASS(*) components correctly.

This issue is related to the ECP ExaAM project.

**Comment by nncarlson** [comment]
This is fixed as of 1efaacf

**Comment by nncarlson** [comment]
Bug still present in 1efaacf

**Comment by nncarlson** [comment]
Bug still present in 62fe54a1

**Comment by nncarlson** [comment]
Here's an analogous vector-valued example which should exit normally, but instead exits on the `STOP 3` statement. If coded similarly to the original example (without the defined constructor) it executes correctly.

```fortran
module any_vector_type

  type :: any_vector
    class(*), allocatable :: value(:)
  end type

  interface any_vector
    procedure any_vector_value
  end interface

contains

  function any_vector_value(value) result(obj)
    class(*), intent(in) :: value(:)
    type(any_vector) :: obj
    allocate(obj%value, source=value)
  end function

end module

program main
  use any_vector_type
  type(any_vector) :: x
  x = any_vector([1,2])
  if (.not.allocated(x%value)) stop 1
  select type (v => x%value)
  type is (integer)
    if (any(v /= [1,2])) stop 2
  class default
    stop 3
  end select
end program
```

**Comment by nncarlson** [comment]
And here's a derived type-valued version of the original example, which should exit normally but instead exits at `STOP 3` due to an incorrect (or missing) assignment of values. Once the original example is fixed, this one should work too.
```fortran
type point
  real a, b
end type

type foo
  class(*), allocatable :: val
end type
type(foo) :: x, y

allocate(x%val, source=point(1.0,2.0))
y = x

select type (p => x%val)
type is (point)
  if (p%a /= 1.0 .or. p%b /= 2.0) stop 1
class default
  stop 2
end select

select type (p => y%val)
type is (point)
  if (p%a /= 1.0 .or. p%b /= 2.0) stop 3
class default
  stop 4
end select

end
```

**Comment by gklimowicz** [comment]
We believe this should be fixed, @nncarlson 
Please let us know if you find otherwise.
