### ISSUE TITLE
ISHFT intrinsic returns incorrect result with INT8 argument

### ISSUE THREAD

**Issue by nncarlson** [flang-compiler/flang#254]
The ISHFT intrinsic returns the incorrect result when right shifting (negative shift value) the bits of an INT8 value whenever the leftmost bit is 1.  Instead of shifting in a 0 bit from the left, it shifts in a 1 bit (or doesn't shift anything in, leaving the leftmost bit unchanged).  Here's an example:
```fortran
program main
  use,intrinsic :: iso_fortran_env
  integer(int8) :: digest
  digest = -44_int8
  write(*,'(i0,"=",b8.8)') digest, digest
  digest = ishft(digest,-1)
  write(*,'(i0,"=",b8.8)') digest, digest
end program
```
The expected output of the program is
```
-44=11010100
106=01101010
```
But flang produces
```
-44=11010100
-22=11101010
```
This doesn't appear to be a problem for INT16 arguments.  I didn't check other kinds.  And ISHFTC appears to work correctly for INT8 arguments, but again I didn't do exhaustive testing.

**Comment by nncarlson** [comment]
My son suggested that flang is probably just doing an *arithmetic* shift rather than a logical shift, which is what Fortran's ISHFT should be.

**Comment by nncarlson** [comment]
This has got to be an easy one -- any possibility of getting this fixed soon?

**Comment by nncarlson** [comment]
This is fixed as of 1efaacf

**Comment by nncarlson** [comment]
Bug is still present in 1efaacf

**Comment by nncarlson** [comment]
@gklimowicz would it be possible to make this a priority? It's got to be a trivial thing to fix, I think.

**Comment by gklimowicz** [comment]
@nncarlson I'll see what we an do, Neil.

**Comment by nncarlson** [comment]
Fixed in the March 2019 binary release. Thanks!
