### ISSUE TITLE
Segfault on sourced allocation of unlimited polymorphic variable

### ISSUE THREAD

**Issue by nncarlson** [flang-compiler/flang#255]
A run-time segfault occurs at the indicated sourced-allocation line in the example below.  If the final procedure for the ITEM type is omitted, there is no segfault and the program completes normally.  Note that there is no point at which the final procedure is called (or should be called), so its not clear why the presence of a final procedure is relevant to the segfault.
```fortran
module item_type

  type :: item
    class(*), allocatable :: value
  contains
    final :: item_delete  ! NO SEGFAULT IF COMMENTED OUT
  end type

contains

  function new_item(value)
    class(*), intent(in) :: value
    type(item), pointer :: new_item
    allocate(new_item)
    print *, 'before segfault'
    allocate(new_item%value, source=value)  ! SEGFAULT HERE
    print *, 'after segfault'
  end function
  
  subroutine item_delete(this)
    type(item), intent(inout) :: this
    print *, 'in final'
  end subroutine

end module

program main
  use item_type
  type(item), pointer :: foo
  foo => new_item(1)
end program
```

**Comment by nncarlson** [comment]
FYI, all of the bug reports I'm making are arising from the small petaca library https://github.com/nncarlson/petaca (which is admittedly some fairly complex F2003 code).  This library is a core dependency of the Truchas code https://gitlab.com/truchas, which is one of the key components of the ECP ExaAM project.

**Comment by pawosm-arm** [comment]
How did you manage to build petaca not hitting this?:

/tmp/yajl_fort-3dbc64.ll:144:45: error: expected value token
        %3 = bitcast i32 (i64*, i64*, [12 x i32])* @ to i8*, !dbg !73
                                                   ^
1 error generated.
make[3]: *** [src/CMakeFiles/petaca.dir/yajl_fort.F90.o] Error 1

**Comment by nncarlson** [comment]
Checkout the flang branch.  I've implemented various workarounds for issues I've encountered so far.  At this point everything compiles, but lots of the unit tests (run ctest) are failing.  Several of the workarounds weren't quite right (enough to make the compiler error go away), so I expect those might cause failures down the road.

**Comment by pawosm-arm** [comment]
Indeed, building from flang branch succeeds and then it fails on 'make test':

```
Running tests...
ctest --force-new-ctest-process
Test project ~/petaca/build
      Start  1: fortran_dynamic_loader
 1/10 Test  #1: fortran_dynamic_loader ...........   Passed    0.01 sec
      Start  2: map_any
 2/10 Test  #2: map_any ..........................***Exception: SegFault  0.04 sec
      Start  3: any_scalar
 3/10 Test  #3: any_scalar .......................***Failed    0.01 sec
      Start  4: any_vector
 4/10 Test  #4: any_vector .......................***Exception: SegFault  0.04 sec
      Start  5: any_matrix
 5/10 Test  #5: any_matrix .......................***Exception: SegFault  0.04 sec
      Start  6: parameter_list
 6/10 Test  #6: parameter_list ...................***Exception: SegFault  0.04 sec
      Start  7: parameter_list_json
 7/10 Test  #7: parameter_list_json ..............   Passed    0.01 sec
      Start  8: state_history
 8/10 Test  #8: state_history ....................   Passed    0.01 sec
      Start  9: secure_hash
 9/10 Test  #9: secure_hash ......................***Exception: SegFault  0.04 sec
      Start 10: timer_tree
10/10 Test #10: timer_tree .......................   Passed    2.79 sec

40% tests passed, 6 tests failed out of 10

Total Test time (real) =   3.03 sec

The following tests FAILED:
          2 - map_any (SEGFAULT)
          3 - any_scalar (Failed)
          4 - any_vector (SEGFAULT)
          5 - any_matrix (SEGFAULT)
          6 - parameter_list (SEGFAULT)
          9 - secure_hash (SEGFAULT)
Errors while running CTest
make: *** [test] Error 8
```

**Comment by nncarlson** [comment]
This compiles without error now in 1efaacf

**Comment by nncarlson** [comment]
Works now as of 8/12/2018.
