### ISSUE TITLE
Flang seems excessively slow

### ISSUE THREAD

**Issue by nncarlson** [flang-compiler/flang#256]
Flang is taking 135 sec to compile a small library that gfortran compiles in 10 sec.  Is that excessively slow for this stage of flang development?  There's no few files that are the source of the slowness; it's generally slow across all files.   Perhaps I need to build flang with some "optimized" options?   (I'm following the README.md instructions exactly.)

**Comment by janusw** [comment]
I also noticed that flang is considerably slower than other compilers.

> Perhaps I need to build flang with some "optimized" options?

I tried to build with `-DCMAKE_BUILD_TYPE=Release` (for all of llvm, clang & flang), but it didn't appear to help much.

**Comment by nncarlson** [comment]
I see no point in leaving this open. I'm sure the slowness is apparent to everyone, and nvidia has much bigger fish to fry with the compiler than this.
