### ISSUE TITLE
fs11, fs12 tests: wrong uname used for AArch64

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#271]

**Comment by pawosm-arm** [comment]
The fs11.mk checks for armv7 which is not the right uname of any of the 64-bit architectures that Flang supports. Should use aarch64 instead (for which luckily, bl is a valid INSN too)

```
$ grep mmul fs11.s | grep bl|tr -s ' ' '\n' |grep -c bl
3
```

**Comment by sscalpone** [comment]
Like this:
==== ta/tests/f90_correct/inc/fs11.mk - work/pgi/tests/f90_correct/inc/fs11.mk ====
15c15
< ifeq ($(findstring armv7l, $(UNAME)), armv7l)
---
> ifeq ($(findstring armv7l, $(UNAME)), aarch64)

**Comment by pawosm-arm** [comment]
armv7 is twice in this line.
I'll check it again later, I need to go now.

**Comment by pawosm-arm** [comment]
As I suspected, this is not the end of the story. The $(UNAME) variable is empty hence $(INSN) still equals 'call'. Somehow it does not affect fs12 test which also reads $(UNAME).

**Comment by sscalpone** [comment]
fs12 doesn't use the value set by the uname code.  It appears those tests are looking to see if the compiler does idiom recognition & calls a fast copy routine.  By inspection, it seems that the compiler is ok but the test is just checking that the code compiles, links, and executes.

**Comment by pawosm-arm** [comment]
I guess apart from adding aarch64 in fs11.mk and fs12.mk, it would be reasonable to add following in the f90_correct (and even mp_correct - just in case) makefile:

UNAME=$(shell uname -m)

**Comment by gklimowicz** [comment]
Fixed in pull request https://github.com/flang-compiler/flang/pull/276
