### ISSUE TITLE
Internal subprogram cannot be passed as argument

### ISSUE THREAD

**Issue by AlexisPerry** [flang-compiler/flang#280]
I appear to have run into a Fortran 2008 feature that is not implemented in Flang or the PGI compiler yet, although it is implemented in GNU and Intel compilers.  The larger code that I am trying build makes heavy use of this feature and working around it will be prohibitively expensive. The following code gives this error when compiled with  Flang: 
```
flang -c types.f90
flang -c module1.f90
F90-S-0084-Illegal use of symbol setall - attempt to CALL a FUNCTION (module1.f90: 22)
F90-S-0439-An internal subprogram cannot be passed as argument - is_zero (module1.f90: 22)
  0 inform,   0 warnings,   2 severes, 0 fatal for my_subroutine
```
The error message for pgfortran is similar:
```
pgfortran -c types.f90
pgfortran -c module1.f90
PGF90-S-0439-An internal subprogram cannot be passed as argument - is_zero (module1.f90: 22)
  0 inform,   0 warnings,   1 severes, 0 fatal for my_subroutine
```
Gfortran and Ifort compile without errors/warnings.

Here is the example code:
types.f90:
```
module types

  implicit none
  public myType

  type myType
     integer :: num
     procedure(setall_int), pointer, nopass :: setall => null()
  end type myType

  abstract interface

     subroutine setall_int(arg,f)
       integer, intent(inout) :: arg

       interface
          pure logical function f(l)
            integer,intent(in) :: l
          end function f
       end interface

     end subroutine setall_int

  end interface

end module types
```

module1.f90:
```
module module1
  implicit none

contains

  subroutine my_subroutine(thing,number)
    use types, only : myType
    type(myType), intent(in) :: thing
    integer, intent(inout) :: number

    integer :: l

    integer :: what(number)

    do l = 1, number
       what(l) = 0
       if (modulo(l, 100).eq.0) then
          what(l) = 1
       end if
    end do ! l                                                                                                                                                   

    call thing%setall(number,is_zero)

  contains
    pure logical function is_zero(l)
      integer,intent(in) :: l

      is_zero = what(l) .eq. 0
    end function is_zero
  end subroutine my_subroutine

end module module1
```

**Comment by certik** [comment]
Here is a simpler test example with the same problem.

nested.f90:
```fortran
module a
implicit none

interface
    subroutine callback()
    end subroutine
end interface

contains

subroutine h(g)
procedure(callback) :: g
call g()
end subroutine

subroutine f()
integer :: i
i = 1
call h(g)
print *, i
contains
    subroutine g()
    i = i + 1
    end subroutine
end subroutine

end module
```
GFortran and Intel compile this module without problems, but `flang` gives:
```
$ flang nested.f90 
F90-S-0439-An internal subprogram cannot be passed as argument - g (nested.f90: 19)
  0 inform,   0 warnings,   1 severes, 0 fatal for f
```

As @AlexisPerry wrote, this missing feature is really tedious to workaround, as one must put the nested subroutine into a global module scope, and then expose all the internal variables that the nested subroutine accesses as global module variables as follows:
```fortran
module a
implicit none

interface
    subroutine callback()
    end subroutine
end interface

integer :: i

contains

subroutine h(g)
procedure(callback) :: g
call g()
end subroutine

subroutine f()
i = 1
call h(g)
print *, i
end subroutine

    subroutine g()
    i = i + 1
    end subroutine

end module
```
Which quickly becomes messy for more complicated cases with lots of variables.

**Comment by mleair** [comment]
Alexis, 

In your examples, you are passing internal procedures to procedure dummy arguments. Does your code also use the assignment of an internal procedure to a procedure pointer? Or does your code exclusively use procedure dummy arguments for your  callbacks?

Thanks,

Mark

**Comment by AlexisPerry** [comment]
Hi Mark.  Sorry for the delay in response.  As far as I'm aware, my code only references the internal procedure via dummy arguments.  What you see in the reproducer I provided is directly analogous to what is used in my code.

Best,
Alexis

**Comment by AlexisPerry** [comment]
Good morning Mark,

I checked with my management, and while LANL has signed the CLA, we have our own internal process to go through before we can open-source any lines of code.  We’re working on it, but at this stage please DO NOT include my reproducer in the open source test directory.  Feel free to use it internally, though.

Best regards,
-- Alexis

**Comment by gklimowicz** [comment]
@certik @AlexisPerry We believe this has been resolved for some time now, so I am closing. Please reopen if you find otherwise.
