### ISSUE TITLE
Nwchem: OpenMP COPYPRIVATE issue

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#306]
While compiling Nwchem-6.6 I'm seeing following error from exp_smp() in flang2:

`F90-S-0000-Internal compiler error. size_of: attempt to size assumed size character 0 (beom.F: 240)`

It is caused by following code:

```
      logical function beom_tag_to_element(t,symbol,element,atn)
      implicit none
      character*16 t
      character*(*) symbol
      character*(*) element
      integer atn

#include "geom.fh"

      logical ok

!$OMP SINGLE
      ok = geom_tag_to_element(t,symbol,element,atn)
!$OMP END SINGLE copyprivate(symbol,element,atn,ok)
      beom_tag_to_element = ok
      return
      end
```

With `symbol` and `element` removed from the COPYPRIVATE list, this code compiles (assuming -fopenmp compilation flag).
The code above works when built by gfortran.

**Comment by pawosm-arm** [comment]
A fix for this is to distinguish CHARACTER(*) typed variables in 'case A_MP_BCOPYPRIVATE:' (i.e. variables for which is_dtype_runtime_length_char(DTYPEG(sptr)) returns true) and call "COPYPRIVATE_PA" for them instead of "COPYPRIVATE_P". The missing third param for "COPYPRIVATE_PA" can be obtained by calling "LEN" on 'ilm'.

Can't provide ready to use patch due to CLA.

**Comment by pawosm-arm** [comment]
NwChem builds (with OpenMP enabled) using flang patched with one of the recent commits: https://github.com/flang-compiler/flang/commit/48fde701530ee6bcf6d928adb02257ca8bef0834

**Comment by sscalpone** [comment]
Yes, that's the commit that addressed this issue.
