### ISSUE TITLE
RAPS16: OpenMP: can't compile parallel region in which some object passed to it is used

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#315]
One more RAPS16 workload issue.

Following program:

```
MODULE PROG
  USE SHAPES
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: FOO

CONTAINS

  SUBROUTINE FOO(C)
    IMPLICIT NONE
    CLASS(CIRCLE) :: C
    INTEGER :: I

    !$OMP PARALLEL DO SCHEDULE(DYNAMIC) PRIVATE(I)
    DO I=1,10
      CALL C%PRINT_RADIUS()
    ENDDO
    !$OMP END PARALLEL DO
  END SUBROUTINE FOO

END MODULE PROG
```

Causes following compiler error, when compiled with -fopenmp:
```
/tmp/prog-52b30a.ll:98:28: error: use of undefined value '%.O0000'
        %22 = bitcast [12 x i32]* %.O0000 to i64*, !dbg !47
```

With PRIVATE(C) added (e.g. `!$OMP PARALLEL DO SCHEDULE(DYNAMIC) PRIVATE(I, C)`) it compiles, but then it segfaults at runtime.

Without -fopenmp flag, it always compiles and runs.

The class module:
```
MODULE SHAPES
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: CIRCLE, PRINT_RADIUS

  TYPE CIRCLE
    REAL :: RADIUS
  CONTAINS
    PROCEDURE :: PRINT_RADIUS
  END TYPE CIRCLE

CONTAINS

  SUBROUTINE PRINT_RADIUS(SELF)
    CLASS(CIRCLE) :: SELF
    PRINT *, "RADIUS=", SELF%RADIUS
  END SUBROUTINE PRINT_RADIUS

END MODULE SHAPES
```

**Comment by pawosm-arm** [comment]
Got another example, this time not a method call but calling a function from parallel region which takes object passed to this parallel region as a parameter:

```
MODULE SHAPES
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: CIRCLE, PRINT_RADIUS

  TYPE CIRCLE
    REAL :: RADIUS
  CONTAINS
    PROCEDURE :: PRINT_RADIUS
  END TYPE CIRCLE

CONTAINS

  SUBROUTINE PRINT_RADIUS(SELF)
    CLASS(CIRCLE) :: SELF
    PRINT *, "RADIUS=", SELF%RADIUS
  END SUBROUTINE PRINT_RADIUS

END MODULE SHAPES

PROGRAM main
  USE SHAPES
  IMPLICIT NONE
  CLASS(CIRCLE), allocatable :: C

  ALLOCATE(C)
  C%RADIUS = 1.0
  CALL FOO(C)

CONTAINS

  SUBROUTINE BAR(C)
    USE SHAPES
    IMPLICIT NONE
    CLASS(CIRCLE) :: C

    CALL C%PRINT_RADIUS()
  END SUBROUTINE BAR

  SUBROUTINE FOO(C)
    USE SHAPES
    IMPLICIT NONE
    CLASS(CIRCLE) :: C
    INTEGER :: I

    !$OMP PARALLEL DO SCHEDULE(DYNAMIC) PRIVATE(I)
    DO I=1,10
      CALL BAR(C)
    ENDDO
    !$OMP END PARALLEL DO
  END SUBROUTINE FOO

END PROGRAM main
```

In the previous example, the method call takes the object as a (hidden) SELF parameter. In the example above a function also takes object as a parameter.
In the LLVM IR code, objects are passed as two parameters: pointer to the object and an array of 12 32-bit integers. It's this second parameter that causes the problems. Usually callled .O0000n, is not properly captured by a function to which parallel region code is outlined.

**Comment by pawosm-arm** [comment]
I've worked out a fix for this one but it only uncovers another bug that manifests itself at the runtime by a segfault in parallel region.

**Comment by janusw** [comment]
The examples here work without error on today's master, just like the one in #330. I guess this issue can be closed ...

**Comment by gklimowicz** [comment]
Per Janus, closing.
