### ISSUE TITLE
'use of undefined value' error with CLASS variable in OMP PARALLEL region

### ISSUE THREAD

**Issue by janusw** [flang-compiler/flang#330]
Consider  this test case:

```
program omp_class
implicit none

type :: t
end type

contains

   subroutine foo(data)
      class(t) :: data
      !$omp parallel
      call bar(data)
      !$omp end parallel
   end subroutine

   subroutine bar(data)
      class(t), intent(in) :: data
   end subroutine

end
```

Compiling this with `flang -mp` gives me:

```
error: use of undefined value '%.O0000'
        %9 = bitcast [12 x i32]* %.O0000 to i64*, !dbg !45
```

**Comment by janusw** [comment]
I think this problem is very similar, if not identical, to #315.

**Comment by pawosm-arm** [comment]
it's the same problem

**Comment by pawosm-arm** [comment]
I've worked out a fix for this one but it only uncovers another bug that manifests itself at the runtime by a segfault in parallel region.

**Comment by janusw** [comment]
> I've worked out a fix for this one

Like to share?

**Comment by pawosm-arm** [comment]
Yep, but note that it's not the end of the story, due to #347 
```
diff --git a/tools/flang1/flang1exe/semfin.c b/tools/flang1/flang1exe/semfin.c
index ffd77a1..6d45971 100644
--- a/tools/flang1/flang1exe/semfin.c
+++ b/tools/flang1/flang1exe/semfin.c
@@ -275,6 +275,12 @@ add_class_arg_descr_arg(int func_sptr, int arg_sptr, int new_arg_position)
       DTYPEP(new_arg_sptr, dtype);
       inject_arg(func_sptr, new_arg_sptr, new_arg_position);
       PARENTP(arg_sptr, new_arg_sptr);
+      if (PARREFG(arg_sptr) && STYPEG(arg_sptr) != ST_CONST)
+        set_parref_flag2(new_arg_sptr, arg_sptr, 0);
       /*OPTARGP(new_arg_sptr, TRUE);*/ /* FS#17571 */
       return TRUE;
     }
```
The whole idea comes from my observation that all the variables captured to outlined parallel region (in flang2) have parref attribute in symtab generated by flang1. Unfortunately, those infamous companions to object variables (.O0000 and alike) aren't associated with objects yet when the parref attribute is normally set. Therefore I added setting this attribute to the companions in the place in flang1 code where the association is made.

**Comment by pawosm-arm** [comment]
Good news for you! the test case quoted in #347 is slightly more demanding than yours, so in case of your code, my patch solves the problem entirely! In your case, object is just passed to a call in the parallel region, so it's interior is never accessed, hence no problematic extra loads!

**Comment by janusw** [comment]
It appears that the error is gone at f4ec466546c6ad37c3c4775bd07d019a212114c1, probably due to 570d7feefb9b0ba4a7804f55aceaf91fbd98eefe. Thanks for fixing, @mleair!
