### ISSUE TITLE
clang is extremely slow

### ISSUE THREAD

**Issue by twang15** [flang-compiler/flang#356]
I build clang-5.0 with -DCMAKE_BUILD_TYPE=Release, following 4-step instructions here.
Then, I build LULESH1.0 serial version (https://codesign.llnl.gov/lulesh/LULESH.cc) with clang++ as follows.
It is a big surprise to me, clang++ takes so long. Any comments? 
I noticed clang binary size is over 1GB, which is also a big surprise.

[twang15@c92 temp]$ time clang++ -v -O3 LULESH.cc 
clang version 5.0.1 (https://github.com/flang-compiler/clang.git 64043d5cec9fb02d1b0fd80c9f2c4e9e4f09cf8f) (https://github.com/llvm-mirror/llvm.git 1368f4044e62cad4316da638d919a93fd3ac3fe6)
Target: x86_64-unknown-linux-gnu
...
..

real	2m21.979s
user	2m21.842s
sys	0m0.081s

**Comment by twang15** [comment]
I download 5.0 release from here http://releases.llvm.org/download.html
The built binary is only around 80MB and is much faster.

[twang15@c92 temp]$ time /home/twang15/LLVM5.0/install/llvm/bin/clang++ -v -O3 LULESH.cc 
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/twang15/LLVM5.0/install/llvm/bin

real	0m3.745s
user	0m3.694s
sys	0m0.038s

**Comment by twang15** [comment]
The root cause may be due to debug symbols.
The following information is different (dump by gdb)

**For Flang 5.0 build**:  (taking very long time for gdb to load symbols)
Reading symbols from /home/twang15/Flang5.0/install/clang/bin/clang-5.0...done.

**For llvm official 5.0 release build:** (load instantly)
Reading symbols from /home/twang15/LLVM5.0/install/llvm/bin/clang-5.0...(no debugging symbols found)...done.

**Comment by twang15** [comment]
Using strip --strip-unneeded clang-5.0, Flang binary size reduced from 1.2G to 143M.
It is faster than original, but still very very slow.

[twang15@c94 temp]$ time /home/twang15/Flang5.0/install/clang/bin/clang++ -O3 LULESH.cc

real    1m20.272s
user    1m20.209s
sys     0m0.041s

**Comment by twang15** [comment]
code size reduction for LLVM5.0 release:

[twang15@c94 bin]$ ls -lh clang-5.0
-rwxr-xr-x 1 twang15 ncsu 82M Jan  6 05:28 clang-5.0
[twang15@c94 bin]$ strip --strip-unneeded clang-5.0
[twang15@c94 bin]$ ls -lh clang-5.0
-rwxr-xr-x 1 twang15 ncsu 69M Jan  6 16:27 clang-5.0

**Comment by xoviat** [comment]
Are you sure that your compiler is optimizing the generated code? `-DCMAKE_BUILD_TYPE=Release` should not include any debugging symbols and should enable full optimization.

**Comment by twang15** [comment]
Thanks for the reminding.

I double-checked that LLVM was not built with -DCMAKE_BUILD_TYPE=Release while clang is.
In the past, I specify -DCMAKE_BUILD_TYPE=Release for llvm where clang is built within llvm build tree. But, Flang is somehow using a separate build tree for each.

Anyway, it is not a bug and my bad.
