### ISSUE TITLE
abinit: Flang fails to compile program with comment lines too long

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#375]
I've encountered this problem while trying to compile abinit: [https://github.com/abinit/abinit](https://github.com/abinit/abinit)

One of the comment lines was particularly long and Flang failed to process it complaining about its length.
As a workaround I had to wrap whole of the comment with #if 0/#endif pair (fortunately it was .F90 not .f90 file).

**Comment by sscalpone** [comment]
Not legal Fortran but the compiler ought to be able to truncate the comment without any side effects.

**Comment by gklimowicz** [comment]
Should be fixed in recent Flang updates.
