### ISSUE TITLE
Segmentation fault using debug option (-g) with flang 

### ISSUE THREAD

**Issue by Deepak-Porwal** [flang-compiler/flang#389]
[test2-gasdev.f90.txt](https://github.com/flang-compiler/flang/files/1855914/test2-gasdev.f90.txt)

Debug option (-g) is useful to get the debug info produced by compiler. 
In case of Flang simple fortran program is failing with -g option even with O0 optimization level. 
I have attached one test case to reproduce the error.

**Comment by gklimowicz** [comment]
Would it be possible to include the mod_kinds module file? We could probably reproduce the relevant part, but I would like to have the exact files you are using to reproduce the error.

Thanks in advance, as they say.

**Comment by Deepak-Porwal** [comment]
Thanks Gary for showing your interest to resolve this bug. 
I have attached the mod_kinds module file.
Also if you wish you can build 554.roms_r of CPU2017 FP benchmark with -g option to reproduce the bug. Specifically source file "gasdev.fppized.f90" of 554.roms_r benchmark should produce segmentation fault. 
[mod_kinds.zip](https://github.com/flang-compiler/flang/files/1709802/mod_kinds.zip)

**Comment by Deepak-Porwal** [comment]
Because of LLVM Version is hardcoded to 4.0 in the lvm/tools/clang/lib/Driver/ToolChains/Flang.cpp, the argument passed to flang2 is picking  DIExpression which is used for LLVM 4.0 version and hence CLANG is complaining for Invalid DIExpression and leads to segmantation fault. 
The issue is fixed now with change of version 4.0 to 5.0 in Flang.cpp file.

Hardcoded value in Flang.cpp-

LowerCmdArgs.push_back("-x"); LowerCmdArgs.push_back("249"); LowerCmdArgs.push_back("40"); // LLVM version

Condition where it was choosing wrong expression in file flang/tools/flang2/flang2exe/lldebug.c-
if (ll_feature_use_5_diexpression(&db->module->ir)) {
 const unsigned add = lldbg_encode_expression_arg(LL_DW_OP_plus_uconst, 0);
} 
else {
 const unsigned add = lldbg_encode_expression_arg(LL_DW_OP_plus, 0);
}
