### ISSUE TITLE
f2003: runtime crash when class method returns value of c_ptr type (was: runtime crash when abstract class method returns derived type value)

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#405]
In a method (of any class) parameters are passed in registers (following Linux ABI calling convention), usually it is 'this' in the first register, first method param in the second register and so on.
When a method returns a value of derived type, one more fist parameter is added making all the expected parameters shifted one register to the right (placing 'this' in the second register, first method param in the third register and so on) and the method is internally converted into subroutine. This is not done for methods returning c_ptr derived type (defined in iso_c_binding module). Unfortunately, callsite code does not take this exception for c_ptr type into account resulting in shifted (to the right) list of parameters passed to the called method. Depending on what the method does with the params, it may went unnoticed or cause segfault or bus error.

**Comment by pawosm-arm** [comment]
Investigated it a bit. What I found reminds me this famous "up is down" scene from "Pirates of the caribbean at world's end"....

**Comment by pawosm-arm** [comment]
Found an 'if' in flang1's lower.c that does exception for derived types imported from iso_c_binding:
```
if (!is_iso_cptr(DTYPEG(gbl.currsub)) && !CFUNCG(gbl.currsub))
```
Removal of 'is_iso_cptr' part causes new problems, so I guess the code generating call site needs to do similar checking.

**Comment by pawosm-arm** [comment]
Also, this bug affects all classes, not only abstract ones.

**Comment by pawosm-arm** [comment]
In flang1's lowerexp.c the A_NDTYPEP(A_LOPG(ast), DT_PTR); expression seems to work for normal functions but it doesn't work for methods... (despite the fact that the execution path goes through that line for both).

**Comment by sscalpone** [comment]
@pawosm-arm , do you have an example of this behavior?

**Comment by pawosm-arm** [comment]
It's RAPS16 code and according to my notes it's fixed by this commit: https://github.com/flang-compiler/flang/commit/3848eea444095a2158441fdbd3c3d6bebe716874 which replaced our internal fix like this:
(begin of reverted patch)
```
--- a/tools/flang1/flang1exe/lowerexp.c
+++ b/tools/flang1/flang1exe/lowerexp.c
@@ -1792,6 +1792,7 @@ lower_function(int ast)
   int unlpoly; /* CLASS(*) */
   int retdesc;
   int bindC_structret = 0;
+  int c_ptr = 0;

   /*  symfunc = A_SPTRG( A_LOPG( ast ) );*/
   symfunc = procsym_of_ast(A_LOPG(ast));
@@ -1941,6 +1942,10 @@ lower_function(int ast)
     break;
   case TY_DERIVED:
   case TY_STRUCT:
+    if (is_iso_cptr(A_DTYPEG(A_LOPG(ast)))) {
+      c_ptr = 1;
+      break;
+    }
     if (CFUNCG(symfunc)) {
       retdesc = check_return(DTYPEG(FVALG(symfunc)));
       if (retdesc != CLASS_MEM && retdesc != CLASS_PTR) {
@@ -2145,7 +2150,9 @@ lower_function(int ast)
   if (funcusecall) {
     ilm = plower("om", UCALL);
   } else {
-    if (bindC_structret) {
+    if (c_ptr) {
+      ilm = plower("om", ltyped(UFUNC, DT_PTR));
+    } else if (bindC_structret) {
       int retdesc = check_return(DTYPEG(FVALG(symfunc)));
       if (retdesc != CLASS_MEM && retdesc != CLASS_PTR) {
         ilm = plower("om", "SFUNC");
```
(end of reverted patch)
The ticket on our side is closed, and new RAPS tickets were opened (and corresponding upstream ticket on github which you can see), no one returned with complains on this, so I guess it can be closed (you may need to consult with the fix author how it was tested by them and if their test is reusable).
