### ISSUE TITLE
OpenMP: ICE: surprising interactions between parallel regions (was: $omp simd directive not recognized)

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#408]
Flang is only able to recognize simd clause but it's failing with ICE when it encounters plain simd directive, which is a part of the standard, e.g.:

```
!$omp simd
          do i = 1,n
            a(i,j) = a(i,j) * b(i,j) * c(i,j)
          end do
```
```
F90-F-0000-Internal compiler error. print_token(): missing token       0
```

**Comment by sscalpone** [comment]
I tried a simple example that didn't have any problems.  Do you have an example that fails?

**Comment by pawosm-arm** [comment]
I compiled the code above separately and to my surprise it built. So it became apparent that it's the surrounding that causes the issue. And this reminded me one past bug report I opened some time ago:

The problem is more serious, it's the same case as I described in https://github.com/flang-compiler/flang/issues/321 - when there are more than one OpenMP parallel region in a single Fortran file, some clashes start to appear causing unexpected interactions between those regions. The code quoted above is a part of following functions containing two OpenMP parallel regions:
```
        subroutine foo(n,j)
          implicit none
          integer, intent(in) :: n,j
          integer :: i
          double precision :: a(n,n),b(n,n),c(n,n)

!$omp parallel do
          do j = 1,n
            call foo(n,j)
          end do
!$omp parallel do

!$omp simd
          do i = 1,n
            a(i,j) = a(i,j) * b(i,j) * c(i,j)
          end do
        end subroutine foo
```

**Comment by pawosm-arm** [comment]
Note that the 'contains' relation may play key role here!

**Comment by pawosm-arm** [comment]
Another symptom of suspicious interaction: having '$omp simd' replaced with '$omp parallel do simd' flang produces binary that segfaults when compiled with -fopenmp. Removal of '$omp parallel do'/'$omp end parallel do' directives from the outer subroutine (named 'sub') results in binary that does not segfault.

**Comment by pawosm-arm** [comment]
#409 and #367 are another examples of surprising interactions within the code.

**Comment by sscalpone** [comment]
A workaround is to rename j in foo to something else, say, k

**Comment by pawosm-arm** [comment]
Can't reproduce with today's master. I guess it's due to this: https://github.com/flang-compiler/flang/commit/3c9c014ee2ea28f3c8f655b31ed54d2dd7312419

**Comment by sscalpone** [comment]
Yes, and address #321 as well
