### ISSUE TITLE
Cannot finish cmake

### ISSUE THREAD

**Issue by pointhi** [flang-compiler/flang#41]
```cmake
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.13") 
-- Flang version: 4.0.0
-- The ASM compiler identification is Clang
-- Found assembler: /home/thomas/JKU/flang/clang/build/bin/clang
-- The Fortran compiler identification is unknown
CMake Error at runtime/flang/CMakeLists.txt:21 (enable_language):
  The CMAKE_Fortran_COMPILER:

    flang

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

It seems like the following line in ```CMakeLists.txt``` does not work as intended on my system:

```cmake
# In order to bootstrap the runtime library we need to skip
# CMake's Fortran tests
SET(CMAKE_Fortran_COMPILER_WORKS 1)
```

I'm using cmake 3.8.0 and working on a x64 Arch Linux system

**Comment by AlexisPerry** [comment]
"-- The Fortran compiler identification is unknown
CMake Error at runtime/flang/CMakeLists.txt:21 (enable_language):
  The CMAKE_Fortran_COMPILER:
    flang
  is not a full path and was not found in the PATH."

When you build the requisite modified clang, it makes a stub for flang and that's what you need to have in your PATH (or specify the full path to) when configuring the Flang build.  Look in the bin directory of where you installed modified clang.

**Comment by pointhi** [comment]
Thanks for this information,
now I was able to compile a first program
