### ISSUE TITLE
Options -nomp and -noFlangLibs not available

### ISSUE THREAD

**Issue by abhijangda** [flang-compiler/flang#414]
I compiled flang for LLVM 4.0 according to the instructions. However, "-nomp" and "-noFlangLibs" options are not available when I do "flang -help". Compiling with "-nomp" still links my program against OpenMP library, even though my program is only a hello world program.

Is there a way to get around this issue?

**Comment by sscalpone** [comment]
The option is:
  -no-flang-libs          Do not link against Flang libraries

You can find -nomp using --help-hidden.
  -nomp                   Do not link with OpenMP library libomp

Linking with -nomp links with libompstub.  This provides versions of OpenMP routines that assume just a single thread.

Using -no-flang-libs does not link in any flang or OpenMP libraries.
