### ISSUE TITLE
[OpenMP] Regression: ICE reference_for_temp: rank mismatched

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#415]
https://github.com/flang-compiler/flang/commit/f06ba56e33cdf5979ec4a425cf6acea098e8635b causes regression:
```
F90-F-0000-Internal compiler error. reference_for_temp: rank mismatched
```
See comment under the commit.

**Comment by sscalpone** [comment]
Hi @pawosm-arm , we think this was fixed with pull request #419 on March 14. Pull request #419 commit is b356fc9.

Would you like to try this compiler with your code?

**Comment by pawosm-arm** [comment]
Indeed, with current master affected code compiles now.

**Comment by sscalpone** [comment]
Thanks @pawosm-arm !
