### ISSUE TITLE
release_60 instructions fail for openmp

### ISSUE THREAD

**Issue by ajmay81** [flang-compiler/flang#428]
Following the build instructions for flang and prerequisites (which previously worked flawlessly with release_50), cmake fails for openmp because apparently one can no longer configure solely the runtime:

    # cd openmp/runtime
    openmp/runtime # git checkout release_60
    Branch release_60 set up to track remote branch release_60 from origin.
    Switched to a new branch 'release_60'
    openmp/runtime # mkdir build && cd build
    openmp/runtime/build # cmake ..
    -- The C compiler identification is GNU 4.8.5
    -- The CXX compiler identification is GNU 4.8.5
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:13 (message):
      Direct configuration not supported, please use parent directory!

**Comment by sscalpone** [comment]
Thanks for pointing out this change in the cmakefile.

I've update the documentation to show "../.." instead of ".." when configuring openmp with cmake.

By the way, the documentation for the build has just moved to the wiki, 
https://github.com/flang-compiler/flang/wiki/Building-Flang

**Comment by ajmay81** [comment]
Thanks, that works. It might be worth making it consistent with all the other prerequisites and not entering the runtime directory at all now the top-level cmake configure is being used, i.e.

    cd openmp
    git checkout release_60
    mkdir build && cd build
    cmake <your custom options> ..

of course it doesn't matter, the end result is the same.

**Comment by sscalpone** [comment]
Glad that works.  I'll revise the instructions in a  few days as you suggest.
