### ISSUE TITLE
Unable to build libpgmath

### ISSUE THREAD

**Issue by nncarlson** [flang-compiler/flang#434]
I've had no problem building flang in the past with the release_50 branches, but I'm running into errors now following the wiki instructions for the release_60 branches with the new libpgmath build step:
```
[  1%] Building C object lib/common/CMakeFiles/mth_256mask_build.dir/mth_256mask.c.o
In file included from /scratch/flang/flang/runtime/libpgmath/build/lib/common/mth_256mask.c:13:
In file included from /scratch/flang/flang/runtime/libpgmath/lib/common/mth_intrinsics.h:262:
In file included from /scratch/flang/flang/runtime/libpgmath/lib/common/mthdecls.h:45:
In file included from /usr/include/math.h:83:
/usr/include/bits/mathcalls.h:63:1: error: unknown type name '__DECL_SIMD___mth_i_dcos'
__MATHCALL_VEC (cos,, (_Mdouble_ __x));
^
/usr/include/math.h:58:3: note: expanded from macro '__MATHCALL_VEC'
  __SIMD_DECL (__MATH_PRECNAME (function, suffix)) \
  ^
/usr/include/math.h:55:31: note: expanded from macro '__SIMD_DECL'
#define __SIMD_DECL(function) __CONCAT (__DECL_SIMD_, function)
                              ^
/usr/include/sys/cdefs.h:88:23: note: expanded from macro '__CONCAT'
#define __CONCAT(x,y)   x ## y
                        ^
<scratch space>:161:1: note: expanded from here
__DECL_SIMD___mth_i_dcos
^
```
Is this something to do with the warning in the wiki instructions "libpgmath on x86 requires a toolchain that understands AVX-512 instructions, such as clang 6.0 or gcc 7.2"? This is on a Fedora 25 system (gcc 6.4.1). However, when configuring and building libpgmath it it using the 6.0 clang installed at a previous step.

I'm off to try again with a newer locally-built gcc, to see if that makes any difference.

**Comment by sscalpone** [comment]
I've been have similar trouble on Ubuntu systems but not Redhat.  We're investigating.

**Comment by janusw** [comment]
I see exactly the same problems here on Ubuntu 16.10 (also using clang 6.0).

**Comment by janusw** [comment]
Using gcc 7.2, I see several warnings like this:

```
[  2%] Building C object lib/common/CMakeFiles/dispatch.dir/dispatch.c.o
In file included from /home/janus/llvm6/flang/runtime/libpgmath/lib/common/dispatch.c:71:0:
/home/janus/llvm6/flang/runtime/libpgmath/lib/x86_64/math_tables/mth_acosdefs.h:92:38: warning: conflicting types for built-in function ‘cacosf’ [-Wbuiltin-declaration-mismatch]
 MTHINTRIN(acos , cs   , em64t      , cacosf                , cacosf                , cacosf                ,__math_dispatch_error)
                                      ^
/home/janus/llvm6/flang/runtime/libpgmath/lib/common/mth_tbldefs.h:176:13: note: in definition of macro ‘MTHINTRIN’
 extern void _f (); \
             ^~
```

and then a segfault:

```
Scanning dependencies of target mth_z2yy
[  2%] Generating mth_z2yy.c
Segmentation fault (core dumped)
lib/common/CMakeFiles/mth_z2yy.dir/build.make:60: recipe for target 'lib/common/mth_z2yy.c' failed
make[2]: *** [lib/common/mth_z2yy.c] Error 139
```

**Comment by janusw** [comment]
The awk segfault on Ubuntu 16.04 can be avoided by replacing the mawk package by gawk, which provides GNU Awk 4.1.3.

With gcc 7.2 I then get the following error:
```
Scanning dependencies of target mth_z2yy_build
[  2%] Building C object lib/common/CMakeFiles/mth_z2yy_build.dir/mth_z2yy.c.o
In file included from /home/janus/llvm5/flang/runtime/libpgmath/lib/common/mthdecls.h:45:0,
                 from /home/janus/llvm5/flang/runtime/libpgmath/lib/common/mth_intrinsics.h:262,
                 from /home/janus/llvm5/flang/runtime/libpgmath/build/lib/common/mth_z2yy.c:19:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:63:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘extern’
 __MATHCALL_VEC (cos,, (_Mdouble_ __x));
 ^
```

That's again the same line that clang chokes on as well, as reported initially by Neil.

**Comment by janusw** [comment]
At 7bde3b4d2a9b65c5df485a2b86f1ebb4b4e512b6, I am able to build libpgmath successfully with gcc 7.2 (the previous problems were supposedly fixed by 7bb58bd092281edb5abed27fe29c76c8dfba4a92). With clang 6 however, I now get multiple errors like this one:

```
/home/janus/llvm6/flang/runtime/libpgmath/lib/x86_64/fast/fastcdiv.h:730:9: error: instruction requires: AVX-512 ISA
        vbroadcastss .Const_mask(%rip), %zmm2
        ^
```

This happens on a Core i7 CPU without AVX support.

**Comment by mcopik** [comment]
I'm having exactly the same problem with libpgmath when building flang with clang. I'm using clang 6.0, the same one built in step 2 of [flang build process](https://github.com/flang-compiler/flang/wiki/Building-Flang). Recent head  dd1e4ba, a little bit old i7-4800MQ with AVX and AVX2 but no AVX-512 support. The compilation fails at `lib/x86_64/fast/fastcdiv.S` with errors simillar to the one already pasted by @janusw.

**Comment by oliver-pola** [comment]
Having the same history here. Had error from first post few weeks ago. Now with updated sources got over this, but stops with "requires: AVX-512 ISA" like @janusw. Also using clang 6.0 built from instructions. Readme only mentions AVX support of the compiler, not the hardware (AVX2 only).

Since I also noticed I now have to build libpgmath first, then flang, I now can't build flang because of path to libpgmath not found (flang compiled few weeks ago). Maybe update of build instructions needed then?

**Comment by nncarlson** [comment]
After a long delay, I'm taking another whack at this.  Started from scratch with updated repos.  Now the flang cmake configure step is failing on me due to a libpgmath issue:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBPGMATH
    linked by target "flangrti_shared" in directory /scratch/flang/flang/runtime/flangrti
```
But building libpgmath is the next step!  Should that now be built before flang?

More generally I'm confused about what compilers should be used in each of the steps. It doesn't seem to be enough to put ${CMAKE_INSTALL_PREFIX}/bin first in your path as the wiki says.
* Step 1 (llvm): presumably gcc, g++ (I'm on Fedora)
* Step 2 (flang-driver): still presumably gcc/g++, and the installed llvm progs
* Step 3 (openmp): gcc/g++ or clang/clang++ from step 2?
* Step 4 (flang): clang/clang++ from step 2?
* Step 5 (libpgmath): ???

**Comment by oliver-pola** [comment]
Now I'm building on an Knights Landing machine with AVX-512, toolchain built as advised
```
-- The C compiler identification is Clang 6.0.1
-- The CXX compiler identification is Clang 6.0.1
-- The ASM compiler identification is Clang
```
less /proc/cpuinfo says
```
model name      : Intel(R) Xeon Phi(TM) CPU 7210 @ 1.30GHz
...
flags           : ... avx512f rdseed adx avx512pf avx512er avx512cd xsaveopt
```
But again I get "error: instruction requires: AVX-512 ISA" building fastcdiv.S

**Comment by JonasToth** [comment]
I can't get a build running too, neither with `spack` nor with manual repository checkout.

I tried gcc7.3, gcc6.4, clang5, clang6, ubuntu 18.04

Same error as nncarlson.

**Comment by kandycs** [comment]
I met the same segment fault issue on ubuntu 18.04, and addressed it  by installing gawk, and removed the old build, and then rebuild it again. 

`[  2%] Generating mth_z2yy.c
cd /home/janus/llvm5/flang/runtime/libpgmath/build/lib/common && awk -v MAX_VREG_SIZE=512 -v TARGET=X8664 -f /home/janus/llvm5/flang/runtime/libpgmath/tools/mth_z2yy.awk > mth_z2yy.c
Segmentation fault (core dumped)
`

**Comment by junghans** [comment]
@kandycs , I was able to reproduce this and I think that is a bug in Ubuntu's default awk interpreter `mawk`, so you should file a bug report with Ubuntu.

**Comment by janusw** [comment]
> /home/janus/llvm6/flang/runtime/libpgmath/lib/x86_64/fast/fastcdiv.h:730:9: error: instruction requires: AVX-512 ISA

Those errors seem to be gone with the current master (45d7aeb5886c5965a8e793ef3fa632e7e73de56c), and I can finally build libpgmath with clang 6 (as well as GCC 7). So from my point of view this issue can be closed.

**Comment by oliver-pola** [comment]
I can confirm that libpgmath and finally flang do build on merge commit 45d7aeb. After same error like @kandycs was fixed by installing gawk on ubuntu 16.04.

**Comment by junghans** [comment]
mawk issue reported here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901477

**Comment by nncarlson** [comment]
I've been able to build libpgmath for a few months now using GCC 7 (haven't tried myself with clang). Since  I was the OP and others are also having success now, I'm going to close. Open a new issue if you have problems building libpgmath.
