### ISSUE TITLE
large allocation with allocate() issues (incl. -Hx,68,0x1)

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#435]
Following code:
``` 
INTEGER                       :: n
DOUBLE PRECISION, ALLOCATABLE :: a(:,:)
n = 1024*32*2
allocate(x(n2,n2),stat=info)
x(1:n,1:n) = 0.0D0
```
…causes segfault in the last line when built with flang (with or without -i8 or -fdefault-integer-8) or older versions of gfortran. It works properly when built with more recent gfortran (no additional flags needed) or PGI compiler when started with -Mlarge_arrays flag. Unfortunately, no such flag is available in flag, fortunately, PGI compiler behaviour can be triggered by sending -x 68 0x1 to flang1 (e.g. -Hx,68,0x1). When this flag is not set, a 32-bit value is used by default to hold nelems value (first param of alloc04 in flang runtime).
Unfortunately, using -Hx,68,0x1 causes problems when a program uses IEEE modules, e.g.:
```
F90-F-0004-Unable to open MODULE file ieee_arithmetic_la.mod (ieee.f90: 2)
```
In order to build those *_la* (large arrays) versions of IEEE modules, I tried to build flang with following FFLAGS/FCFLAGS: -Hx,68,0x1 -DDESC_I8. This unfortunately causes cmake-specific problems at build time:
```
cmake -E cmake_copy_f90_mod include/ieee_exceptions runtime/flang/CMakeFiles/flang_static.dir/ieee_exceptions.mod.stamp GNU
Error copying Fortran module "include/ieee_exceptions".  Tried "include/IEEE_EXCEPTIONS.mod" and "include/ieee_exceptions.mod".
make[3]: *** [runtime/flang/CMakeFiles/flang_static.dir/ieee_exceptions_la.F95.o.provides.build] Error 1
```

**Comment by gklimowicz** [comment]
This should be working now with the -Mlarge-arrays changes. Here's an example program that shows the allocations working. Note that you need to check the result of the allocation before attempting the assignment. Your sample doesn't do that, which seems questionable to me.

```
program flang435
  integer :: n
  integer :: stat_var = 0
  double precision, allocatable :: x(:,:)

  n = 256
  stat_var = 0
  do while (n <= 1024*64 .and. stat_var == 0)
      print *, 'When n =', n
      allocate(x(n,n),stat=stat_var)
      if (stat_var .eq. 0) then
          print *, 'Array x(n,n) allocated'
          x(1:n,1:n) = 0.0D0
          deallocate (x)
      else
          print *, 'Array x not allocated, stat_var = ', stat_var
      end if
      n = n*4
  end do
end
```

With current flang, I get the following output:
```
$ flang flang435.f90 && ./a.out
 When n =          256
 Array x(n,n) allocated
 When n =         1024
 Array x(n,n) allocated
 When n =         4096
 Array x(n,n) allocated
 When n =        16384
 Array x(n,n) allocated
 When n =        65536
 Array x not allocated, stat_var =             1
```

Both flang and gfortran get segfaults if you don't check that the allocation status is zero before assigning to the array.

Or am I missing the point of your issue?

**Comment by pawosm-arm** [comment]
You're right, I pasted incomplete example. The complete program works now when compiled with flang.

**Comment by gklimowicz** [comment]
Thanks Paul.
