### ISSUE TITLE
Not able to build flang

### ISSUE THREAD

**Issue by hcltrajesh** [flang-compiler/flang#443]
Greetings!
I am a newbie to the world of LLVM. I have been trying to build flang (in debug mode) for about a week.

I am following each and every thing that is mentioned on below URL:
https://github.com/flang-compiler/flang/wiki/Building-Flang
I tried with release_60 as well as release_50.
I was able to build llvm, flang driver, openmp in debug mode.
But, while building flang I am getting the below error:
Scanning dependencies of target flang_shared
**[ 37%] Building Fortran object runtime/flang/CMakeFiles/flang_shared.dir/iso_c_bind.F95.o
gfortran: error: unrecognized command line option '-Mreentrant'
make[3]: *** [runtime/flang/CMakeFiles/flang_shared.dir/iso_c_bind.F95.o] Error 1
make[2]: *** [runtime/flang/CMakeFiles/flang_shared.dir/ieee_exceptions.F95.o.provides] Error 2
make[1]: *** [runtime/flang/CMakeFiles/flang_shared.dir/all] Error 2
make: *** [all] Error 2**

Please help me move further from this point.

Thanks in anticipation!
Rajesh

**Comment by sscalpone** [comment]
It appears that gfortran is being used to compile iso_c_bind.F95.  That won't work.  Make sure that flang is on your PATH. When building flang, your PATH must include the install bin directory.

**Comment by hcltrajesh** [comment]
Thanks for your response! I reviewed my steps and found  that i missed to specify -DCMAKE_Fortran_COMPILER=<INSTALL_PREFIX>/bin/flang.
Thanks a lot.
