### ISSUE TITLE
[Regression] "Illegal number or type of arguments" for pure procedure

### ISSUE THREAD

**Issue by janusw** [flang-compiler/flang#446]
Please consider this example:

```
program p

   call foo(bar)

CONTAINS


   pure logical function bar(x, y)
      integer, intent(in) :: x, y
      bar = .false.
   end function

   subroutine foo(arg)
      interface
         logical function arg(x, y)
            integer, intent(in) :: x, y
         end function
      end interface
   end subroutine

end
```

flang recently complains:
```
F90-S-0074-Illegal number or type of arguments to foo - arguments of bar and arg do not agree (test.f90: 3)
  0 inform,   0 warnings,   1 severes, 0 fatal for p
```

Obviously the arguments *do* agree. It seems that flang is actually confused by the PURE attribute, but this is not mentioned in the error message.

I believe the usage of PURE here is standard conforming: Passing a pure procedure to a non-pure argument is ok, while passing a non-pure procedure to a pure argument is forbidden (this is confirmed by gfortran, ifort and pgfortran).

**Comment by janusw** [comment]
@gklimowicz It turns out the regression was introduced by commit eb5b8d36d68a44194c89259d039bd8dea67405ee: Before that revision, at least the following variant of the test case was accepted:

```
module m

contains

   pure logical function bar(x, y)
      integer, intent(in) :: x, y
      bar = .false.
   end function

   subroutine foo(arg)
      interface
         logical function arg(x, y)
            integer, intent(in) :: x, y
         end function
      end interface
   end subroutine

end


program p
   use m
   call foo(bar)
end
```

The original test case was rejected with `F90-S-0439-An internal subprogram cannot be passed as argument` (which is an acceptable diagnostic wrt F03 IIUC).

**Comment by gklimowicz** [comment]
We'll look into this, Janus.

**Comment by janusw** [comment]
Great, thank you!

**Comment by gklimowicz** [comment]
Janus: Can you tell us if this was found while compiling an application we should know about?

**Comment by janusw** [comment]
Hi Gary,

the code that this bug was found on is a closed-source CFD code, so I can not share it with you in full glory. But what I can do (and have been doing) is to report any bugs that come up (with reduced test cases).

Currently our application can not be fully compiled with flang yet (only with gfortran and ifort), but I certainly hope that flang will get there soon. Apart from this bug, our main blocker is #370 right now, and to a minor extent #360 and #330.

Cheers,
Janus

**Comment by gklimowicz** [comment]
Thanks, Janus. This is very helpful. And especially thanks for the reproducers.

**Comment by janusw** [comment]
Fixed by 39a6cc3 (thanks!). Closing.

**Comment by mleair** [comment]
janusw,

Can we include your example as a test in flang/test ?

Thanks,

Mark

**Comment by janusw** [comment]
> Can we include your above test case as a test in flang/test ?

Certainly! Please do ...

**Comment by gklimowicz** [comment]
Couple of quick questions, Janus. I want to make sure our ducks are in a row, as they say.
1. Would it be a problem for you to submit a contributor license agreement so we can accept the test?
2. Is there any particular copyright notice (or license) that you need for the test?
