### ISSUE TITLE
Manually linking LLVM IR with clang

### ISSUE THREAD

**Issue by jjgarzella** [flang-compiler/flang#463]
I would like to manually link LLVM IR generated by flang with IR generated by clang. I use LLVM 3.9 for both flang and clang, and for both I enable debug symbols with the -g option. When I try to link, I get the following error:

    ERROR: linking module flags 'Debug Info Version': IDs have conflicting behaviors

I can fix the issue by manually going in and changing the LLVM constant for Debug Info Version in the `.ll` file generated by flang. However, I need a more robust and automatable solution.

Example:

main.f90

```
program main
  implicit none
  interface
    subroutine c_function() bind(c)
    end subroutine c_function
  end interface
  print *, "Hello from Fortran!!"
  call c_function()
end
```

c_file.c
```
#include "stdio.h"

void c_function() {
    printf("Hello from C!!\n");
}
```

Command sequence:
```
flang -S -g -O0 -emit-llvm main.f90
clang -S -g -O0 -emit-llvm c_file.c
llvm-link -S -v -o program.ll *.ll
```

And the whole output:
```
Loading 'c_file.ll'
Linking in 'c_file.ll'
Loading 'main.ll'
Linking in 'main.ll'
WARNING: linking module flags 'Dwarf Version': IDs have conflicting values
ERROR: linking module flags 'Debug Info Version': IDs have conflicting behaviors
```

**Comment by simoatze** [comment]
For starting we do not support Flang with LLVM 3.9.

But here some possible workarounds:

It looks like both the DWARF version and the Debug Info version differ, so you can try to adding “-gdwarf-2” on Clang compilation to force it generates Dwarf2 (by default Clang generates Dwarf4).

Another workaround is to compile to object files (rather than LLVM-IR), and link the .o files into an executable with flang.

Let us know if that helps!

**Comment by jjgarzella** [comment]
I tried using -gdwarf-2 and it worked to eliminate the warning about Dwarf. However, the Debug Info version still is causing an issue. 

Part of the problem is that SMACK needs the files in LLVM IR format for translation purposes, so compiling into a .o file won't work unless there is some way to lift the .o file into LLVM IR.

**Comment by sscalpone** [comment]
Be careful when testing this issue because
`llvm-link -S -v -o program.ll *.ll`
may pick up program.ll twice if program.ll already exists.
