### ISSUE TITLE
[OpenMP][RAPS16] runtime failure on PARALLEL WORKSHARE directive

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#474]
Following program:
```
program workshare
  implicit none
  integer :: somevals(65535)

  !$OMP PARALLEL WORKSHARE
    somevals(:) = 0.0
  !$OMP END PARALLEL WORKSHARE
end program
```
causes following assertion in libomp.so at runtime:
```
Assertion failure at kmp_sched.cpp(97): plastiter && plower && pupper && pstride.
OMP: Error #13: Assertion failure at kmp_sched.cpp(97).
```
Values obtained by the runtime:
plastiter (nil), plower 1, pupper 65535, pstride 1

Tried different versions of libomp.so and the bug persists.

**Comment by pawosm-arm** [comment]
It's not a regression, it never actually worked. RAPS16 execution path that leads to this code was never reached due to other bugs.

**Comment by pawosm-arm** [comment]
Seems like it's fixed by https://github.com/flang-compiler/flang/commit/4814d7317622b33e40cd2429184f4a680eca45c9

**Comment by gklimowicz** [comment]
Paul, do you have a copyright and license for the reproducer? We would like to add it to Flang.

(Maybe there is one we can use from other submissions, but I want to check first.)

**Comment by pawosm-arm** [comment]
Given generic variable name (someval) it's not a code taken literally from RAPS, it's just a generic snippet that reproduces the same behavior. I'm not sure this kind of generic code needs any licensing, not from my side at least.
