### ISSUE TITLE
[large arrays] potential regression: warnings while building IEEE modules

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#492]
These warnings started to appear during flang runtime library compilation after applying large arrays patch:
```
[ 31%] Building Fortran object runtime/flang/CMakeFiles/flang_static.dir/I8_sources/ieee_arithmetic.F95.o
F90-W-0006-Input file empty (build_dir/runtime/flang/I8_sources/ieee_arithmetic.F95)
[ 31%] Building Fortran object runtime/flang/CMakeFiles/flang_static.dir/I8_sources/ieee_exceptions.F95.o
F90-W-0006-Input file empty (build_dir/runtime/flang/I8_sources/ieee_exceptions.F95)
```

**Comment by vjayathirtha-nv** [comment]
Looks like the issue shows up when the Clang that gets built as a part of flang, is used. You can use gcc as C compiler to bypass this issue, while this is being addressed.

**Comment by pawosm-arm** [comment]
It's still in the build logs. Yet it doesn't make any harm, so I'm closing it.
