### ISSUE TITLE
compiling for apple arm64?

### ISSUE THREAD

**Issue by gaming-hacker** [flang-compiler/flang#509]
hello everyone,

before going down a long hard road, has anyone successfully built a fortran library that will work with apple's arm64?

**Comment by sscalpone** [comment]
I have not.  Nor have I heard that anyone else has tried.  But my ears are tuned to HPC not phones or embedded.

**Comment by gaming-hacker** [comment]
if you knew how bad the apple accelerate framework and blas implementations are; then lacking even basic bessel/hankel functions  you might be in the same boat as me 

:-)
