### ISSUE TITLE
[OpenMP][WRF but not from SPEC2017] segfault when writing to THREADPRIVATE string

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#515]
Following code (frame/module_domain.F) segfaults at WRITE statement when the whole thing is built with -fopenmp:
```
        WRITE(wrf_err_message,*)&
            'alloc_space_field: domain ',id,', ',num_bytes_allocated,' bytes allocated'
        CALL  wrf_debug( 0, wrf_err_message )
```
where `wrf_err_message` is imported from other module in which it's declared OpenMP THREADPRIVATE (frame/module_wrf_error.F):
```
MODULE module_wrf_error
  INTEGER           :: wrf_debug_level = 0
  CHARACTER*256     :: wrf_err_message
...
    integer, parameter :: min_allowed_buffer_size=200
!$OMP THREADPRIVATE (wrf_err_message)
CONTAINS
...
```

As expected, the WRITE statement results in f90io_ldw_intern_init() call into the flang runtime (runtime/flang/ldwrite.c). For some reason, both CADR(cunit) and CLEN(cunit) are both zero, unless `!$OMP THREADPRIVATE (wrf_err_message)` line is removed. This clearly results in segfault on dereferencing CADR(cunit) down the line.

Note that when I prepared small reproducer candidate, it worked, for any number of threads (in my reproducer I placed WRITE statement in a parallel region), so the interference must come from somewhere else, hence it requires more creative approach to nail it:
```
module wrfmod
  implicit none
  CHARACTER*256     :: wrf_err_message
  !$OMP THREADPRIVATE (wrf_err_message)
end module wrfmod

program wrf
  use wrfmod
  implicit none
  INTEGER(KIND=8)  :: num_bytes_allocated
  INTEGER            :: id

  id = 0
  num_bytes_allocated = 0
!$OMP PARALLEL
  WRITE(wrf_err_message,*)&
    'alloc_space_field: domain ',id,', ',num_bytes_allocated,' bytes allocated'
  WRITE (*, *) wrf_err_message
!$OMP END PARALLEL
end program wrf
```

**Comment by gklimowicz** [comment]
Paul, we've been unable to reproduce this recently. Can you check it again on your end?

**Comment by pawosm-arm** [comment]
No, still segfaults:
```
$ flang -fopenmp -c wrfmod.f90
$ flang -c wrf.f90
$ flang -fopenmp -o wrf wrf.o wrfmod.o
$ ./wrf
Segmentation fault (core dumped)
$
```

**Comment by gklimowicz** [comment]
Aha. Fails only on Arm, I suspect. Correct?

**Comment by pawosm-arm** [comment]
I don't know about x86_64 or Power, they may be just lucky.
We had internal discussion here and concluded that it's in general wrong idea to access OpenMP THREADPRIVATE variables outside of OpenMP parallel regions (that's what happening in wrf.f90 if you don't build it with -fopenmp), e.g. removal of !$OMP PARALLEL/END PARALLEL from wrf.f90 results in segfault even if it's compiled with -fopenmp.
How gfortran could get away with that is not clear to me.

**Comment by AlexisPerry** [comment]
Is it possible that gfortran treats the `!$OMP THREADPRIVATE (wrf_err_message)` as a comment in this case, and since that line isn't the only place `wrf_err_message` is declared, everything is ok?

**Comment by pawosm-arm** [comment]
WRF should fix their Makefiles to either always using or always not using -fopenmp. No worth to replicate gfortran's behavior as it only endorses wrong compilation attempts.
