### ISSUE TITLE
Compiler error when building siesta application

### ISSUE THREAD

**Issue by kiranchandramohan** [flang-compiler/flang#531]
Siesta (https://launchpad.net/siesta) is an open source application for electronic structure calculations and ab initio molecular dynamics simulations.

The following internal error is produced by the compiler while compiling the file Src/m_mixing.F90 in the Siesta application.
```
/tmp/m_mixing-13a554.ll:358: error: use of undefined type named 'struct.BSS12'
%5 = bitcast %struct.BSS12* @.BSS12 to i64*
```
The lines in questions are:
```
call fake_history_from_linear(mix%next)
call fake_history_from_linear(mix%next_conv)
```
where the module variables are defined higher up in the module initialisation section as:
```
! The next mixing method following this method
type(tMixer), pointer :: next => null()

! The next mixing method following this method
type(tMixer), pointer :: next_conv => null()
```

Note : If the save statement is removed then the compilation passes successfully.

**Comment by pawosm-arm** [comment]
I'm able to build m_mixing.F90 of siesta-4.1-b4 without errors or warnings.

**Comment by kiranchandramohan** [comment]
Thanks, @pawosm-arm for informing. Thanks, @gklimowicz for the fix.
