### ISSUE TITLE
RAPS17: libemos: integer constant must have integer type

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#544]
While building RAPS17's libemos (libemos-4.5.4-Source/interpolation/hll2ll.F):
```
hll2ll-ed23d4.ll:7: error: integer constant must have integer type
@.STATICS1 = internal global %struct.STATICS1 <{ [40 x i8]   [i8 255, i8 255, i8 255, i8 255, i8 0, i8 0, i8 0, i8 0, i8 255, i8 255, i8 255, i8 255, i8 0,i8 0,i8 0,i8 0, i8 0,i8 0,i8 0,i8 0,i8 0,i8 0,i8 0,i8 0, i8 0,i8 0,i8 0,i8 0,i8 0,i8 0,i8 0,i8 0, i8 255, i8 255, i8 255, i8 255, i8 0,i8 0,i8 0,i8 0],  i8*  -1 }>, align 16, !dbg !73, !dbg !78, !dbg !108, !dbg !112, !dbg !138

1 error generated.
```
More details soon.

**Comment by sscalpone** [comment]
What compilation options did you use? Did you narrow the change in behavior to a specific commit?

**Comment by pawosm-arm** [comment]
No compilation options are needed, just -c. Also I removed all `#include` lines (note that `implicit none` needs to be removed then), so the bug is narrowed to single F77 file: interpolation/hll2ll.F (you can copy it outside source tree and work on it separately) which contains 450 lines and DATA and SAVE statements.

**Comment by pawosm-arm** [comment]
Got smallest reproducer (minimal.f):

```
      PROGRAM MINIMAL
      IMPLICIT NONE
      REAL OLD(1)
      POINTER(IOLD, OLD)
      DATA IOLD/-1/
      END PROGRAM MINIMAL
```
Fails as such:
```
/tmp/minimal-735d2c.ll:5:55: error: integer constant must have integer type
@.STATICS1 = internal global %struct.STATICS1 <{ i8*  -1 }>, align 16
                                                      ^
1 error generated.
```
Remove the DATA line and the program will compile.

**Comment by pawosm-arm** [comment]
Note that gfortran requires use of `-fcray-pointer` for successful compilation of the code above. Adding the same flag to flang does not help and causes following warning:
```
clang-6.0: warning: argument unused during compilation: '-fcray-pointer' [-Wunused-command-line-argument]
```

**Comment by pawosm-arm** [comment]
IR bridge should make use of inttoptr, something like:
@.STATICS1 = internal global %struct.STATICS1 <{ i8* inttoptr (i32 -1 to i8*) }>, align 16
