### ISSUE TITLE
Flang compile time option to get optimization information

### ISSUE THREAD

**Issue by hcltrajesh** [flang-compiler/flang#558]
Hello,

Apologies, as I am posting my query as an issue.
I am trying to find compile time options for flang that I can use to get optimization messages explaining the applied optimizations for a specific statement in a test case. I think "-hmsgs" option of cray compiler writes optimization messages on stderr.

For example:
> vim optimize.f90
integer::arr1(10),arr2(10),res(10)
arr1=1
arr2=1
do j= 1, 10
arr1(j)=j
arr2(j)=j
do i=1,10
res(i) = arr1(i) + arr2(i)
end do
end do
print*,res
end

Compiled as follows:
> flang optimize.f90 -O3

In the case above, SIMD conversion might be applied, loop unrolling might be applied etc.
**Do we have a flang compile time option which can display optimization information.**

Thanks in anticipation,
Rajesh

**Comment by flang-cavium** [comment]
flang -fsave-optimization-record 

You can then process the resulting *.yaml file with LLVM's opt-viewer.py and view the optimization details in a browser.

**Comment by sscalpone** [comment]
@vjayathirtha-nv Is "-fsave-optimization-record" option supported with flang?

**Comment by flang-cavium** [comment]
It should be:

https://github.com/flang-compiler/flang-driver/pull/19
