### ISSUE TITLE
cpu2017 wrf runtime error

### ISSUE THREAD

**Issue by shivaramrao** [flang-compiler/flang#567]
After the following commit cpu2017 wrf crashes with segment violation.
-------------------------------------------------------------------------------------------
commit 244ed8e8feca54c811b21f75459182dd0e842868
Author: Gary Klimowicz <gklimowicz@pobox.com>
Date:   Mon Jul 23 08:49:57 2018 -0700

    When we call a procedure that has a character argument targets,
    we add a length argument at the end of the argument list.
    This can conflict with the recent addition of procedure argument
    descriptors which may also appear at the end of an argument
    list. To fix this problem, move all procedure descriptor arguments
    to the very end of the argument list; past the character length
    arguments.

    Fixes Flang issue #501.
---------------------------------------------------------------------------------------------

The crash occurs at following point, possibly due to invalid procedure descriptors.

 SUBROUTINE open_w_dataset ( id , fname , grid , config_flags , outsub , sysdepinfo, ierr )
   ...
   CALL outsub( id , grid , config_flags , ierr )
the address of outsub is corrupted at the time of call.

following ir level differences are seen:
before the change:
define void @module_io_domain_open_w_dataset_(i64* noalias %id, i64* noalias %fname, i64* noalias %grid, i64* noalias %config_flags, i64* noalias %outsub, i64* noalias %sysdepinfo, i64* noalias %ierr, i64* noalias nocapture readonly %"outsub$sd", i32 %.U0038.arg, i32 %.U0039.arg) local_unnamed_addr #1

after the change:
define void @module_io_domain_open_w_dataset_(i64* noalias %id, i64* noalias %fname, i64* noalias %grid, i64* noalias %config_flags, i64* noalias %outsub, i64* noalias %sysdepinfo, i64* noalias %ierr, i32 %.U0038.arg, i32 %.U0039.arg, i64* noalias nocapture readonly %"outsub$sd") local_unnamed_addr #

**Comment by mleair** [comment]
Please provide the dummy argument declarations to SUBROUTINE open_w_dataset ( id , fname , grid , config_flags , outsub , sysdepinfo, ierr ).

Thanks!

**Comment by shivaramrao** [comment]
The dummy argument declarations is here:

 SUBROUTINE open_w_dataset ( id , fname , grid , config_flags , outsub , sysdepinfo, ierr )
   TYPE (domain)             :: grid
   CHARACTER*(*) :: fname
   CHARACTER*(*) :: sysdepinfo
   INTEGER      , INTENT(INOUT) :: id , ierr
   TYPE(grid_config_rec_type),  INTENT(IN   )    :: config_flags
   LOGICAL , EXTERNAL :: wrf_dm_on_monitor
  ..

**Comment by pawosm-arm** [comment]
Doesn't fail with current master. Maybe it's because my similar test case provided with #501 also doesn't fail with current master. Can you check that it works for you too?

**Comment by sscalpone** [comment]
Both 521.WRF and 621.WRF are working for me.
