### ISSUE TITLE
Flang cannot print an allocatable array

### ISSUE THREAD

**Issue by kargl** [flang-compiler/flang#580]
program foo
   implicit none
   integer, allocatable :: y1(:),y2(:)
   integer :: l1,l2,i
   y1 = [1, 2, 3]
   y2 = [1, 2, 3, 4, 5]
   l1 = size(y1)
   l2 = size(y2)
   y2 = [y2, [(0,i=1,l1-l2)]]
   y1 = [y1, [(0,i=1,l2-l1)]]
   print *, y1
   print *, y2
end program foo
% flang -o z -O a.f90 && ./z
Segmentation fault (core dumped)
% flang -o z a.f90 && ./z
Segmentation fault (core dumped)

(lldb) run ./z
Process 34337 launching
Process 34337 launched: './z' (x86_64)
Process 34337 stopped
* thread #1, name = 'z', stop reason = signal SIGSEGV: invalid address (fault address: 0xffffffffffff91f8)
    frame #0: 0x0000000000400c8b z`MAIN_ at a.f90:5
   2       implicit none
   3       integer, allocatable :: y1(:),y2(:)
   4       integer :: l1,l2,i
-> 5       y1 = [1, 2, 3]
   6       y2 = [1, 2, 3, 4, 5]
   7       l1 = size(y1)
   8       l2 = size(y2)

**Comment by OliverPerks** [comment]
I think you will need to force F2003 allocatable semantics.
-Mallocatable=03      Select Fortran 03 semantics for assignments to allocatable objects
As it defaults to 95.

**Comment by kargl** [comment]
OliverPerks, The flang wiki states

"Flang single-core and OpenMP performance is now on par with GNU Fortran. Flang has implemented Fortran 2003 and has a near full implementation of OpenMP through version 4.5 targeting multicore CPUs."

So, Flang is neither a Fortran 2003 compiler nor on par with GNU Fortran.

If the default behavior is Fortran 95 semantics with some Fortran 2003 features supported, then Flang should not claim to be a Fortran 2003 compiler.

**Comment by bryanpkc** [comment]
`-Mallocatable=03` has been the default since flang-compiler/flang-driver@bf423ebfea2b0d8476f13b3e21812e523ff79073 (December 2018). I guess we can close this issue.
