### ISSUE TITLE
Enhancement: directive !DIR$ fixedformlinesize needed by official OpenMP headers

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#583]
Normally, flang exposes its own version of omp_lib.h which works fine with flang.
There are users that insist on using omp_lib.h matching and provided with chosen OpenMP runtime library.
Unfortunately, LLVM's OpenMP runtime library exposes official omp_lib.h with lines too long, requiring addition of -Mextend in all affected Makefiles of old codebase. Also flang's mp_correct tests (they're started with -Mfixed) can't be started with official omp_lib.h unless -Mextend is added to their command line.
To address the issue of lines too long, omp_lib.h uses following directive:
```
!DIR$ fixedformlinesize:132
```
which is not supported by flang.

**Comment by sscalpone** [comment]
Why not push a request to reformat omp_lib.h?

**Comment by pawosm-arm** [comment]
Done: https://bugs.llvm.org/show_bug.cgi?id=38839

**Comment by pawosm-arm** [comment]
I don't think they're capable to fix it properly...

**Comment by sscalpone** [comment]
Why don't you submit the fix?

**Comment by pawosm-arm** [comment]
Not in this sprint, it's fully packed with tasks.

**Comment by pawosm-arm** [comment]
My suggestions were listened to, I guess we may close this one.
