### ISSUE TITLE
-My,164,0x800000 flag results in much more utilization of LLVM intrinsics producing significantly faster code

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#591]
As in the topic. This was found while investigating dramatic loss of performance in fatigue2 and mp_prop_design benchmarks from polyhedron suite.

**Comment by sscalpone** [comment]
On ARM? Why?  Use more words :)

**Comment by pawosm-arm** [comment]
Yes, we do our runs on ARM64 machines. What we observed in generated LLVM IR is that the faster code is full of calls to LLVM-IR intrinsics (llvm. prefixed names) an later on they result in inlined code (so there is far less calls to libm functions). In slower LLVM IR code we see only the calls to libpgmath using new naming style.

**Comment by pawosm-arm** [comment]
It's not that the LLVM-IR intrinsics are faster, it's the problem that libpgmath functions are slower.
