### ISSUE TITLE
Some do concurrent related errors missing from errmsg-in.n

### ISSUE THREAD

**Issue by kiranchandramohan** [flang-compiler/flang#598]
Several 'do concurrent' related errors are missing from errmsg-in.in

This causes emitting off errors with "Unknown error code". Sample test case.
```
program mn
  call concur()
contains
  subroutine concur()
    integer i
    do concurrent (i=1:10)
      if(i .eq. 3) then
        exit ok
      end if
    end do
ok: if(i .eq. 3) then
      print *, 'Success'
    end if ok
  end subroutine
end program
```
Examples of code calling unknown errors.
tools/flang1/flang1exe/semant3.c:          error(1042, ERR_Severe, gbl.lineno, "DO CONCURRENT", CNULL);
tools/flang1/flang1exe/semant3.c:        error(1050, ERR_Severe, gbl.lineno, "EXIT from", CNULL); // 2018-C1166
tools/flang1/flang1exe/semant3.c:        error(1051, ERR_Severe, gbl.lineno, SYMNAME(sptr), CNULL); // 2018-C1140
tools/flang1/flang1exe/semant3.c:          error(1052, ERR_Severe, gbl.lineno, ieee_name[i], CNULL);
tools/flang1/flang1exe/semant3.c:            error(1053, ERR_Severe, gbl.lineno, "FORALL", CNULL);

**Comment by gklimowicz** [comment]
Kiran,

Yes, we noticed this a few days ago and have a fix ready to be pushed to Flang in our next collection of bug fixes (should be by close of business tomorrow).

**Comment by gklimowicz** [comment]
Kiran, can you see if this is working now for you?

**Comment by kiranchandramohan** [comment]
Thanks @gklimowicz, this is working fine now. I do not see any errors with Unknown error code. Closing the issue.
