### ISSUE TITLE
LAPACK testing errors

### ISSUE THREAD

**Issue by danielleontiev** [flang-compiler/flang#599]
I've just compiled LAPACK library with `flang` using suggestions from the last comment from [here].(https://github.com/flang-compiler/flang/issues/128)

I used `-O3` optmization. Moreover, I've done the same using `gfortran`.
Here is testing summary from LAPACK tests:

`gfortran`:

            -->   LAPACK TESTING SUMMARY  <--
        Processing LAPACK Testing output found in the TESTING directory
    SUMMARY             nb test run  numerical error     other error  
    ================    =========== =================   ================  
    REAL                1292645     0   (0.000%)        0   (0.000%)    
    DOUBLE PRECISION    1293457     0   (0.000%)        0   (0.000%)    
    COMPLEX             752816      0   (0.000%)        0   (0.000%)    
    COMPLEX16           752536      1   (0.000%)        1   (0.000%)    

    --> ALL PRECISIONS  4091454     1   (0.000%)        1   (0.000%)

`flang`:

            -->   LAPACK TESTING SUMMARY  <--
        Processing LAPACK Testing output found in the TESTING directory
    SUMMARY             nb test run  numerical error     other error  
    ================    =========== =================   ================  
    REAL                499084      612 (0.123%)        227 (0.045%)    
    DOUBLE PRECISION    574172      372 (0.065%)        198 (0.034%)    
    COMPLEX             531199      204 (0.038%)        5   (0.001%)    
    COMPLEX16           605768      126 (0.021%)        0   (0.000%)    

    --> ALL PRECISIONS  2210223     1314 (0.059%)       430 (0.019%)

`flang` fails much more test ***Comparing to*** `gfortran` (there are only 0.059% of tests failed but it's 0% for gfortran), is it critical and how it influences on precision of calculations?

**Comment by gklimowicz** [comment]
Daniel, can you try this with the -Kieee option to flang when compiling? Higher levels of optimization like -O3 can default to using the fastmath routines in our libpgmath library. These might produce results with less precision than you are getting in gfortran (which lacks fastmath support).

**Comment by d-parks** [comment]
Hi Daniel,
If you suspect the runtime math library, specifying the environment variable MTH_I_STATS=4 will give you a list of which actual functions are called along with frequency counts.  It might help you narrow down the issue.

**Comment by danielleontiev** [comment]
@gklimowicz thanks a lot for pointing out on `-Kieee` option. Here is testing summary:

                -->   LAPACK TESTING SUMMARY  <--
            Processing LAPACK Testing output found in the TESTING directory
    SUMMARY             nb test run  numerical error     other error  
    ================    =========== =================   ================  
    REAL                1265717     4   (0.000%)        0   (0.000%)    
    DOUBLE PRECISION    1293457     0   (0.000%)        0   (0.000%)    
    COMPLEX             752816      0   (0.000%)        0   (0.000%)    
    COMPLEX16           753628      0   (0.000%)        0   (0.000%)    

    --> ALL PRECISIONS  4065618     4   (0.000%)        0   (0.000%)

Errors are gone but unfortunately disabling fastmath has decreased the speed of LAPACK routines as expected. But in average `flang` is still faster comparing to `gfortran` in LAPACK tests. Here is the results:

| Output file   | Test name                                                             |   | gfortran | flang | flang (fastmath disabled) |
|---------------|-----------------------------------------------------------------------|---|----------|-------|---------------------------|
|               |                                                                       |   |          |       |                           |
| cbak.out      | .. test output of CGEBAK ..                                           |   | 0        | 0     | 0                         |
| cbal.out      | .. test output of CGEBAL ..                                           |   | 0        | 0     | 0                         |
| cbb.out       | Tests of CGBBRD                                                       |   | 0.06     | 0.07  | 0.07                      |
| ccsd.out      | Tests of the CS Decomposition routines                                |   | 0.02     | 0.02  | 0.02                      |
| cec.out       | Tests of the Nonsymmetric eigenproblem condition estimation routines  |   | 0.07     | 0.07  | 0.08                      |
| ced.out       | Tests of the Nonsymmetric Eigenvalue Problem Driver                   |   | 0.47     | 0.5   | 0.55                      |
| cgbak.out     | .. test output of CGGBAK ..                                           |   | 0        | 0     | 0                         |
| cgbal.out     | .. test output of CGGBAL ..                                           |   | 0        | 0     | 0                         |
| cgd.out       | Tests of the Generalized Nonsymmetric Eigenvalue Problem Driver CGGEV |   | 0.57     | 0.57  | 0.64                      |
| cgg.out       | Tests of the Generalized Nonsymmetric Eigenvalue Problem routines     |   | 0.21     | 0.2   | 0.31                      |
| cglm.out      | Tests of the Generalized Linear Regression Model routines             |   | 0.02     | 0.03  | 0.03                      |
| cgqr.out      | Tests of the Generalized QR and RQ routines                           |   | 0.07     | 0.07  | 0.08                      |
| cgsv.out      | Tests of the Generalized Singular Value Decomposition routines        |   | 0.04     | 0.05  | 0.04                      |
| clse.out      | Tests of the Linear Least Squares routines                            |   | 0.01     | 0.01  | 0.01                      |
| cnep.out      | Tests of the Nonsymmetric Eigenvalue Problem routines                 |   | 0.32     | 0.34  | 0.36                      |
| csb.out       | Tests of CHBTRD                                                       |   | 0.04     | 0.05  | 0.04                      |
| cse2.out      | Tests of the Hermitian Eigenvalue Problem routines                    |   | 1.6      | 1.42  | 1.47                      |
| csep.out      | Tests of the Hermitian Eigenvalue Problem routines                    |   | 1.56     | 1.32  | 1.36                      |
| csg.out       | Tests of the Hermitian Eigenvalue Problem routines                    |   | 1.38     | 1.48  | 1.56                      |
| csvd.out      | Tests of the Singular Value Decomposition routines                    |   | 18.07    | 3.13  | 17.24                     |
| ctest.out     | Tests of the COMPLEX LAPACK routines                                  |   | 23.09    | 18.76 | 21.64                     |
| ctest_rfp.out | Tests of the COMPLEX LAPACK RFP routines                              |   | 1.93     | 1.44  | 1.58                      |
| dbak.out      | .. test output of DGEBAK ..                                           |   | 0        | 0     | 0                         |
| dbal.out      | .. test output of DGEBAL ..                                           |   | 0        | 0     | 0                         |
| dbb.out       | Tests of DGBBRD                                                       |   | 0.04     | 0.05  | 0.04                      |
| dcsd.out      | Tests of the CS Decomposition routines                                |   | 0.01     | 0.02  | 0.01                      |
| dec.out       | Tests of the Nonsymmetric eigenproblem condition estimation routines  |   | 1.02     | 0.69  | 0.89                      |
| ded.out       | Tests of the Nonsymmetric Eigenvalue Problem Driver                   |   | 0.34     | 0.37  | 0.37                      |
| dgbak.out     | .. test output of DGGBAK ..                                           |   | 0        | 0     | 0                         |
| dgbal.out     | .. test output of DGGBAL ..                                           |   | 0        | 0     | 0                         |
| dgd.out       | Tests of the Generalized Nonsymmetric Eigenvalue Problem Driver DGGES |   | 0.53     | 0.55  | 0.52                      |
| dgg.out       | Tests of the Generalized Nonsymmetric Eigenvalue Problem routines     |   | 0.13     | 0.18  | 0.13                      |
| dglm.out      | Tests of the Generalized Linear Regression Model routines             |   | 0.02     | 0.02  | 0.02                      |
| dgqr.out      | Tests of the Generalized QR and RQ routines                           |   | 0.04     | 0.05  | 0.04                      |
| dgsv.out      | Tests of the Generalized Singular Value Decomposition routines        |   | 0.03     | 0.04  | 0.03                      |
| dlse.out      | Tests of the Linear Least Squares routines                            |   | 0.01     | 0.01  | 0.01                      |
| dnep.out      | Tests of the Nonsymmetric Eigenvalue Problem routines                 |   | 0.2      | 0.23  | 0.38                      |
| dsb.out       | Tests of DSBTRD                                                       |   | 0.04     | 0.04  | 0.03                      |
| dse2.out      | Tests of the Symmetric Eigenvalue Problem routines                    |   | 2.29     | 1.79  | 1.83                      |
| dsep.out      | Tests of the Symmetric Eigenvalue Problem routines                    |   | 1.23     | 1.33  | 1.38                      |
| dsg.out       | Tests of the Symmetric Eigenvalue Problem routines                    |   | 1.48     | 1.56  | 1.51                      |
| dstest.out    | Tests of the DOUBLE PRECISION LAPACK DSGESV/DSPOSV routines           |   | 2.07     | 1.93  | 1.56                      |
| dsvd.out      | Tests of the Singular Value Decomposition routines                    |   | 17.04    | 16.65 | 16.36                     |
| dtest.out     | Tests of the DOUBLE PRECISION LAPACK routines                         |   | 8.62     | 9.59  | 9.28                      |
| dtest_rfp.out | Tests of the DOUBLE PRECISION LAPACK RFP routines                     |   | 0.61     | 0.62  | 0.61                      |
| sbak.out      | .. test output of SGEBAK ..                                           |   | 0        | 0     | 0                         |
| sbal.out      | .. test output of SGEBAL ..                                           |   | 0        | 0     | 0                         |
| sbb.out       | Tests of SGBBRD                                                       |   | 0.03     | 0.05  | 0.04                      |
| scsd.out      | Tests of the CS Decomposition routines                                |   | 0.01     | 0.01  | 0.01                      |
| sec.out       | Tests of the Nonsymmetric eigenproblem condition estimation routines  |   | 0.69     | 0.72  | 0.71                      |
| sed.out       | Tests of the Nonsymmetric Eigenvalue Problem Driver                   |   | 0.28     | 0.3   | 0.29                      |
| sgbak.out     | .. test output of SGGBAK ..                                           |   | 0        | 0     | 0                         |
| sgbal.out     | .. test output of SGGBAL ..                                           |   | 0        | 0     | 0                         |
| sgd.out       | Tests of the Generalized Nonsymmetric Eigenvalue Problem Driver SGGES |   | 0.39     | 0.42  | 0.41                      |
| sgg.out       | Tests of the Generalized Nonsymmetric Eigenvalue Problem routines     |   | 0.1      | 0.15  | 0.1                       |
| sglm.out      | Tests of the Generalized Linear Regression Model routines             |   | 0.01     | 0.01  | 0.01                      |
| sgqr.out      | Tests of the Generalized QR and RQ routines                           |   | 0.03     | 0.03  | 0.03                      |
| sgsv.out      | Tests of the Generalized Singular Value Decomposition routines        |   | 0.02     | 0.02  | 0.02                      |
| slse.out      | Tests of the Linear Least Squares routines                            |   | 0.01     | 0.01  | 0.01                      |
| snep.out      | Tests of the Nonsymmetric Eigenvalue Problem routines                 |   | 0.16     | 0.18  | 0.17                      |
| ssb.out       | Tests of SSBTRD                                                       |   | 0.02     | 0.03  | 0.03                      |
| sse2.out      | Tests of the Symmetric Eigenvalue Problem routines                    |   | 0.95     | 1.08  | 1.19                      |
| ssep.out      | Tests of the Symmetric Eigenvalue Problem routines                    |   | 0.88     | 1.01  | 1.01                      |
| ssg.out       | Tests of the Symmetric Eigenvalue Problem routines                    |   | 0.95     | 1.1   | 1.05                      |
| ssvd.out      | Tests of the Singular Value Decomposition routines                    |   | 9.83     | 2.38  | 10.45                     |
| stest.out     | Tests of the REAL LAPACK routines                                     |   | 7.57     | 7.54  | 8.3                       |
| stest_rfp.out | Tests of the REAL LAPACK RFP routines                                 |   | 0.57     | 0.58  | 0.59                      |
| zbak.out      | .. test output of ZGEBAK ..                                           |   | 0        | 0     | 0                         |
| zbal.out      | .. test output of ZGEBAL ..                                           |   | 0        | 0     | 0                         |
| zbb.out       | Tests of ZGBBRD                                                       |   | 0.08     | 0.08  | 0.1                       |
| zcsd.out      | Tests of the CS Decomposition routines                                |   | 0.03     | 0.03  | 0.03                      |
| zctest.out    | Tests of the COMPLEX*16 LAPACK ZCGESV/ZCPOSV routines                 |   | 5.06     | 4.72  | 4.13                      |
| zec.out       | Tests of the Nonsymmetric eigenproblem condition estimation routines  |   | 0.11     | 0.07  | 0.07                      |
| zed.out       | Tests of the Nonsymmetric Eigenvalue Problem Driver                   |   | 0.81     | 0.7   | 0.71                      |
| zgbak.out     | .. test output of ZGGBAK ..                                           |   | 0        | 0     | 0                         |
| zgbal.out     | .. test output of ZGGBAL ..                                           |   | 0        | 0     | 0                         |
| zgd.out       | Tests of the Generalized Nonsymmetric Eigenvalue Problem Driver ZGGEV |   | 0.79     | 0.85  | 0.81                      |
| zgg.out       | Tests of the Generalized Nonsymmetric Eigenvalue Problem routines     |   | 0.3      | 0.31  | 0.3                       |
| zglm.out      | Tests of the Generalized Linear Regression Model routines             |   | 0.03     | 0.03  | 0.03                      |
| zgqr.out      | Tests of the Generalized QR and RQ routines                           |   | 0.09     | 0.09  | 0.09                      |
| zgsv.out      | Tests of the Generalized Singular Value Decomposition routines        |   | 0.06     | 0.06  | 0.06                      |
| zlse.out      | Tests of the Linear Least Squares routines                            |   | 0.02     | 0.02  | 0.02                      |
| znep.out      | Tests of the Nonsymmetric Eigenvalue Problem routines                 |   | 0.46     | 0.51  | 0.49                      |
| zsb.out       | Tests of ZHBTRD                                                       |   | 0.05     | 0.05  | 0.05                      |
| zse2.out      | Tests of the Hermitian Eigenvalue Problem routines                    |   | 2.24     | 2.38  | 2.28                      |
| zsep.out      | Tests of the Hermitian Eigenvalue Problem routines                    |   | 2.85     | 2.26  | 2.17                      |
| zsg.out       | Tests of the Hermitian Eigenvalue Problem routines                    |   | 2.06     | 2.3   | 2.16                      |
| zsvd.out      | Tests of the Singular Value Decomposition routines                    |   | 28.01    | 29.22 | 24.59                     |
| ztest.out     | Tests of the COMPLEX*16 LAPACK routines                               |   | 31.6     | 30.86 | 27.84                     |
| ztest_rfp.out | Tests of the COMPLEX*16 LAPACK RFP routines                           |   | 2.56     | 1.99  | 1.92                      |
|               |                                                                       |   |          |       |                           |
| Summary:      |                                                                       |   | 184.99   | 157.4 | 174.35                    |

**Comment by kargl** [comment]
Daniel, your table is meaningless.  What do the numbers indicate?  What options did you use with gfortran and flang?

BTW, contrary to gklimowicz's statement, gfortran does have a -ffast-math option and -Ofast option.  Whether these options are of use is left as an exercise to the reader as these option may permit gfortran to violate certain requirements of the Fortran standard.

**Comment by gklimowicz** [comment]
@kargl Thank you for clarifying what I really intended to mean.
