### ISSUE TITLE
[Debug] Regression in debug for automatic arrays

### ISSUE THREAD

**Issue by kiranchandramohan** [flang-compiler/flang#606]
The commit (https://github.com/flang-compiler/flang/commit/cd1a75b4edd87e51c6e561da66915eb95b7ba990) disables generation of a llvm.dbg.declare. This dbg.declare connects an artificial variable to the upper bound of the automatic array. We cannot print the array without this dbg.declare.

To reproduce the issue, print the array (arr) in gdb by breaking on the print statement.
    
```
subroutine automatic_1d( x, arr)
  implicit none
  integer :: x
  integer :: arr(x)

  print *,"automatic_1d: "," = ",arr
end subroutine

program mn
integer arr(10)
arr = 3
call automatic_1d(10, arr)
end program
```

**Comment by gklimowicz** [comment]
This should have been fixed in PR#636. @kiranchandramohan let me know if this is not the case.
