### ISSUE TITLE
[Debug] Use statements not processed for debug metadata generation

### ISSUE THREAD

**Issue by kiranchandramohan** [flang-compiler/flang#607]
Current implementation of module variables debug generation does not process use statements. This causes the following issues
1) Only if a module variable occurs in the code will the debug appear. Presence of a use statement is not enough.
Breakpoint 1, main () at use_mod.f90:8
8       print *, "hello"
(gdb) p a
$1 = ( (0, 1045149306), 1.2904777690891933e-08 )
```
module vars
integer :: a = 1
integer :: b = 2
end module

program main
use vars
print *, "hello"
end program
```
2) Restricted import of module variables is not supported.
Breakpoint 1, main () at use_mod.f90:8
8       print *, a
(gdb) p b
$1 = 2
```
module vars
integer :: a = 1
integer :: b = 2
end module

program main
use vars, only : a
print *, a
end program
```
3) Renaming of module variables is not supported.
Breakpoint 1, main () at use_mod.f90:8
8       print *, acopy
(gdb) p a
$1 = 1
(gdb) p acopy
No symbol "acopy" in current context.
```
module vars
integer :: a = 1
integer :: b = 2
end module

program main
use vars, only : acopy => a
print *, acopy
end program
```

**Comment by gklimowicz** [comment]
Kiran, is this resolved to your satisfaction? We believe we pushed the necessary changes for this May 15th.

**Comment by kiranchandramohan** [comment]
Thanks @gklimowicz, @jiel-nv. I can confirm that the issue is fixed. Closing.
