### ISSUE TITLE
subroutine internal variables 

### ISSUE THREAD

**Issue by shivaramrao** [flang-compiler/flang#609]
In the following program, it is expected str to have same address at f1 and f2.  but flang prints different addresses indicating that different storage location is used for str at internal subroutine.

subroutine f1(a)
  implicit none
  integer :: a
  CHARACTER(LEN=a) :: str
  print *,loc(str)
  call f2()
  contains
     subroutine f2()
     implicit none
     print *,loc(str)
     end subroutine

end subroutine

program main
integer :: a
print *,loc(a)
call f1(10)
call f1(12)
end program

If a constant length array is declared along with save attribute, the address is same across internal functions.
e.g:
  CHARACTER(LEN=128), save :: str

**Comment by gklimowicz** [comment]
We're investigating this...

**Comment by shivaramrao** [comment]
The problem may be with the following function
     flang1/flang1exe/semsym.c:set_internref_flag()

I believe, this function is supposed to set the subroutine internal flag for this array. but it skips it when DTY(DTYPEG(sptr)) == TY_CHAR

Addition of following code make the testcase work.  
    if (DTY(DTYPEG(sptr)) == TY_ARRAY || POINTERG(sptr) || ALLOCATTRG(sptr) ||
+      DTY(DTYPEG(sptr)) == TY_CHAR || DTY(DTYPEG(sptr)) == TY_NCHAR ||

Please ignore if this is not the correct fix.
