### ISSUE TITLE
Broken links in Release Notes.rst

### ISSUE THREAD

**Issue by rouson** [flang-compiler/flang#61]
The following hyperlinks in [ReleaseNotes.rst] are broken:

* [the Flang Team](http://flang.nvidia.com/)
* [Flang 0.0 Release Notes](http://flang.nvidia.com/releases/0.0/tools/flang/docs/ReleaseNotes.html)
* [Flang Web Site](http://flang.nvidia.com/)

[ReleaseNotes.rst]: https://github.com/flang-compiler/flang/blob/master/docs/ReleaseNotes.rst

**Comment by rouson** [comment]
** ping **  I would be glad to submit a pull request with the corrected links, but I haven't been able to determine the links.

**Comment by sscalpone** [comment]
Fixed the broken links here: 25541006a36ba5548945f0ea592b9a2a196bf57c

We'll update the top-page when the mailing list, web site, etc are set up.  Not ETA yet.
