### ISSUE TITLE
Segfault in program with allocatables at O2 and above

### ISSUE THREAD

**Issue by kiranchandramohan** [flang-compiler/flang#630]
At higher optimization levels (O2 and above) the executable for the program given below segfaults. Note that the program does not segfault,
1) with ulimit -s unlimited
2) when compiled with Mallocatable=95 .
3) when compiled at O1 or below.

After some investigation, I see that temporary arrays are created for the copies of the allocatable variables in the program. And the copies are allocated on stack at higher optimization levels as the sizes of the arrays are known at compile time. Since the arrays are huge, I believe the stack runs out of space. 

```
program mem
implicit none
call calc
contains
subroutine calc
  real(kind=8), allocatable :: a(:),b(:)
  allocate (a(600000),b(600000))
  a=sqrt(a)
  b=sqrt(b)
end subroutine calc
end program mem
```

**Comment by gklimowicz** [comment]
I think these are indicative of "features".

With 1995 allocatable semantics, we're not reallocating the arrays on assignments to a and b.

I haven't looked at the generated object code, but I suspect there's an optimization to stack allocate the temporaries so we can vectorize the calculations at higher optimization levels.

Though unexpected, I think the behavior is conformant.

**Comment by kiranchandramohan** [comment]
Thanks @gklimowicz for confirming that this is conformant behaviour.
As you say this is a bit unexpected since a program which ran fine previously now segfaults after the switch to allocatable semantics. Is there a flag to allocate the copy on the heap? And can allocation on stack be tied to the Mstack_arrays flag?

**Comment by gklimowicz** [comment]
@kiranchandramohan We have no plans to make an option like -Mnostack_arrays force everything to be allocated on the heap...

**Comment by kiranchandramohan** [comment]
Thanks @gklimowicz.
