### ISSUE TITLE
Flang does not support a commonly used c-fortran interfacing pattern

### ISSUE THREAD

**Issue by kiranchandramohan** [flang-compiler/flang#631]
Consider the Fortran (bc.f90) and C (a.c) files given below. In this program the C code calls two subroutines in Fortran,
i) The first one which directly calls a Fortran subroutine (b) works fine.
ii) The second one calls a Fortran subroutine (c), passing it a pointer to the subroutine b. Subroutine 'c' calls 'b' and it is this call that segfaults.

We are told that this is a commonly used c-fortran interfacing pattern and works fine with the Intel, Gfortran and NAG compilers.

```
/*a.c*/
#include <stdlib.h>
int main()
{
  extern void b_(char*,long);
  extern void c_(void (char*,long),char*,long);
  char msg[20] = "Hello from b\n";
  long msgLen = 20;
  b_(msg,msgLen);
  msg[11] = 'c';
  c_(b_,msg,msgLen);
  exit (0);
}
```

```
!bc.f90
    Subroutine b(msg)
      Implicit None
      Character (*), Intent (In) :: msg

      Print *, msg
      Return
    End Subroutine

    Subroutine c(b, msg)
      Implicit None
      Interface
        Subroutine b(msg)
          Character (*), Intent (In) :: msg
        End Subroutine
      End Interface
      Character (*), Intent (In) :: msg

      Call b(msg)
      Return
    End Subroutine
```

```
clang -c a.c
flang -c bc.f90
flang -o bc bc.o a.o
$ ./bc
 Hello from b
Segmentation fault
```

**Comment by kiranchandramohan** [comment]
While other compilers may support this, it is a non-standard usage of C-Fortran interfacing. There is no plan to fix this in Flang. The F18 implementation will support this use case.

**Comment by gklimowicz** [comment]
I would say "the F18 implementation of procedure pointers is planned to be different than the current implementation, and this use case may be supported." I wouldn't like to commit at this time to guaranteeing that the use case will be supported.
