### ISSUE TITLE
Flang support which standard about Fortran （F77、90、95、2018）

### ISSUE THREAD

**Issue by Jasonmessage** [flang-compiler/flang#633]
Hello,

     Apologies, as I am posting my query as an issue.
     Now I am trying to compile the Fortran porgram, but need to know which fortran standard flang support.but i can't find detailed infomation about supported language standard.so please list the supported language standard(F77、90、95、2018) when you are convenient! thanks!

Looking forward to your reply soon!

**Comment by gklimowicz** [comment]
Flang supports Fortran 2003 with some features of Fortran 2008. The status of F2008 features in Flang can be found in the wiki at https://github.com/flang-compiler/flang/wiki/Fortran-2008.

**Comment by Jasonmessage** [comment]
Hi gklimowicz，
    Thank for your reply ! flang support fortran 2003 and some features of fortran 2008 .
    but flang whether support fortran 77、90、95 ?

**Comment by gklimowicz** [comment]
Yes, Jason, you should find full support for the older versions of Fortran as well.

**Comment by Jasonmessage** [comment]
Hi gklimowicz，
    You mean that flang can't be sure whether support the older versions of Fortran，so i need to verify full support for the older versions of Fortran!

**Comment by d-parks** [comment]
Hi Jason,

I believe that Gary is saying that Flang has full support for the versions of Fortran you inquired about.

What is your concern?

**Comment by Jasonmessage** [comment]
Hi David，

    thanks, I just want to confirm what Gary is saying！

**Comment by Jasonmessage** [comment]
In additional，the AHC compiler of ARM also list some supported features of Fortran 2008 and AHC compiler is base on flang.
       I find that ARM support more features of Fortran 2008 by comparing [https://github.com/flang-compiler/flang/wiki/Fortran-2008](url) and [https://developer.arm.com/products/software-development-tools/hpc/arm-fortran-compiler/fortran-2008-status](url)
      So i want to know whether flang has included the more features that ARM has supported，and whether ARM has committed request for merging the more features that ARM AHC compiler has supported.

**Comment by gklimowicz** [comment]
I believe Arm and Flang support the same Fortran 2008 features. Our documentation on this wiki may be a bit out of date, as we were recently doing a deep dive on F2008 feature status. The update to the wiki here should happen soon.

The Arm folk should be able to tell us if they have implemented anything beyond what NVIDA had committed to Flang.

**Comment by Jasonmessage** [comment]
Gary , thanks!

**Comment by Jasonmessage** [comment]
Hi Gary,

    Flang have the plan to support quad precision ( real * 16 and so on) ?

**Comment by Jasonmessage** [comment]
Thank you!
