### ISSUE TITLE
flangrti: libnuma stubs exported by Flang runtime library

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#653]
flangrti part of Flang runtime library contains numa.c file full of libnuma functions stubs. This results in potential link-time problem for those who link against real libnuma. Since flang frontend does not seem to emit calls to those functions, I'd suggest to remove them (along with whole numa.c file) from the project.

**Comment by sscalpone** [comment]
Including numa.c in the flang library is wrong.  We'll remove it soon.

**Comment by benbenolson** [comment]
I've been hunting this bug down for several days. I had no idea why all of my code no longer works in Fortran applications. This needs to be removed ASAP, as it quietly breaks any code that links against `libflang`. Why don't you just link `libflang` against *actual* `libnuma`?

**Comment by gklimowicz** [comment]
@pawosm-arm Please let me know if this is still an issue for you. We believe it's fixed.

**Comment by pawosm-arm** [comment]
It is fixed (and closed).
