### ISSUE TITLE
Regression in module procedure redefinition

### ISSUE THREAD

**Issue by RichBarton-Arm** [flang-compiler/flang#699]
Since pull request #681 the following incorrect code is now accepted by flang without error. Previously the errors
>F90-S-0043-Illegal attempt to redefine symbol bad (hh_repro.f90: 6)
>F90-W-0155-MODULE PROCEDURE not defined: bad (hh_repro.f90: 10)

```
module mod
   interface operator (+)
      module procedure add
   end interface
  interface
    integer function add(a,b)
    end function
  end interface
end module
```
The code is essentially redefining the _add_ function in mod that has been implicitly declared with the _module procedure_ line with a reference to an external function of the same name. 

Bisecting indicates that this regression was introduced by [this commit](https://github.com/flang-compiler/flang/commit/37e6062d969bf337b964fe8119767046fcbdcdfa)

**Comment by gklimowicz** [comment]
@RichBarton-Arm This should be fixed. Can you confirm?

**Comment by RichBarton-Arm** [comment]
/install/bin/flang test.f90 
F90-S-1212-add was previously declared to be a module procedure. (test.f90: 6)
  0 inform,   0 warnings,   1 severes, 0 fatal for mod

Looks good - thanks!
