### ISSUE TITLE
error: invalid field 'flags' on DIGlobalVariable node

### ISSUE THREAD

**Issue by RichBarton-Arm** [flang-compiler/flang#718]
Since pr#705, the following example code produces an error when built with -g

```
! Reproducer.f90:
program comm
common /c1/ var1, var2
var1=10
end program
```
> flang reproducer.f90  -c -g
/tmp/reproducer-04b53a.ll:50:89: error: invalid field 'flags'
!25 = distinct !DIGlobalVariable(scope: !20, name: "c1", type: !24, isDefinition: true, flags: 64)

I think this is due to commit https://github.com/flang-compiler/flang/commit/ab96fee2f2b66525886d188c88519d42ff19c19a which came in this pull request.

Is it possible that an additional patch to flang/llvm is needed that adds the 'flags' field to this type of node to make this work correctly?

**Comment by sscalpone** [comment]
@RichBarton-Arm Just to confirm, are you using the latest flang-compiler/llvm?  Which branch?

**Comment by RichBarton-Arm** [comment]
@sscalpone Sorry, I should have mentioned that. 

I am using release_70 branch on the latest commit:
"Merge pull request #66 from schweitzpgi/release_70"

**Comment by jiel-nv** [comment]
I will take a look.

**Comment by gklimowicz** [comment]
flang-driver pull request 71 and llvm pull request 71 (9 days ago) should have resolved this. Rich, can you check release_70 again, please?
