### ISSUE TITLE
TBAA: wrf miscomparison

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#72]
Given following example Fortran code:
```
        PROGRAM MAIN
          IMPLICIT NONE
          REAL, DIMENSION(0:50) :: PXL
          INTEGER :: I

          DO I = 0,50
            PXL(I) = I
          ENDDO
          CALL FOO(PXL,50,2.)
        END PROGRAM

        SUBROUTINE FOO(BUF, LAST, LIMIT)
          IMPLICIT NONE
          REAL, DIMENSION(0:LAST), INTENT(IN) :: BUF
          INTEGER, INTENT(IN) :: LAST
          REAL, INTENT(IN) :: LIMIT

          REAL, DIMENSION(0:LAST) :: TMP
          REAL :: RES
          INTEGER :: J

          RES = 0.
          DO J = 0,LAST
            TMP(J) = BUF(J)
            IF (TMP(J).LT.LIMIT) THEN
              CALL BAR(TMP(J))
            ENDIF
            RES = RES + TMP(J)
          ENDDO

          PRINT *, 'res=', RES
        END

        SUBROUTINE BAR(X)
          IMPLICIT NONE
          REAL, INTENT (INOUT) :: X
          X = X + 5.5
        END
```
Result printed when built with:
```
    gfortran -O0, -O1 or -O2: res= 1286.00000
    flang -O0 or -O1: res= 1286.000
    flang -O2: res= 1275.000

```
The failure looks to be caused by invalid TBAA information generated by flang.

The test generates different results when built with -O2. By manually disabling load elimination within llvm (via DisableGVNLoadPRE) and comparing the resulting IR, you can see that when "bar" is inlined into "foo" the store within L.LB2_361 is assumed not to alias with the load in L.LB2_328 and so the wrong value is used when eliminating the load in L.LB2_331. Looking at the address generation for the memory accesses proves the addresses to be identical but this fact is ignored because of the attached TBAA metadata.

The accesses within block L.LB2_361 are tagged with "!tbaa !10" with relevant the matching accesses within L.LB2_328 and L.LB2_331 tagged with !tbaa !8. Looking at the metadata within either of those files shows there to be no "parent relation" between these tags and thus can be considered non-aliasing. This is not true as "bar" is directly accessing storage allocated under "foo".

**Comment by pawosm-arm** [comment]
WorksForMe

**Comment by pawosm-arm** [comment]
Unfortunately, we're experiencing significant performance drop with this patch applied!

**Comment by pawosm-arm** [comment]
Although the latest patch ("Performance improvement" commit) fixes the initial case, unfortunately it does not solve the problem entirely. We're still seeing wrongly emitted LLVM IR in cases where functions get inlined. This could happen for example when building GAMESS project.

**Comment by schweitzpgi** [comment]
Are you using LLVM 5.0?

**Comment by pawosm-arm** [comment]
Yes

**Comment by schweitzpgi** [comment]
You may want to back out the commit @305938 (from LLVM) and see if that helps at all.

**Comment by pawosm-arm** [comment]
We're pulling form upstream frequently, so it's already tested... Apparently, the TBAA metadata generated by Flang is sometimes wrong.

**Comment by sscalpone** [comment]
WRF as been stable for us since Septebmer.  How about you @pawosm-arm ?

**Comment by pawosm-arm** [comment]
I'd agree WRF is not an issue anymore in this ticket, it's all about cross-LLVM TBAA refactor now and AFAIR there is one more ticket (#317) regarding current state of TBAA.
