### ISSUE TITLE
Intermediate/temporary files (*.dbg) left around when compiled with -g

### ISSUE THREAD

**Issue by kiranchandramohan** [flang-compiler/flang#727]
Intermediate/temporary files with suffix *.dbg are being left around when compiled with -g. This started happening after the following PR was merged into flang-driver.
https://github.com/flang-compiler/flang-driver/pull/54

The issue can be reproduced with a simple hello-world program when compiled with -g.
```
> cat hello.f90
program hello
  implicit none
  print*, "Hello World!"
end program hello
> flang hello.f90 -g
> ls
 hello.f90
 hello-2ce6f7.dbg
 a.out
```

**Comment by vjayathirtha-nv** [comment]
With [a recent commit](https://github.com/flang-compiler/flang/commit/ffa3355173efe9ac536446a4155ff5daeb369e52), this issue no longer exists. Can you close this @gklimowicz ?

**Comment by gklimowicz** [comment]
This should be fixed in Flang now.
