### ISSUE TITLE
Array constructor use results in internal compiler error. interf:new_symbol_and_link, symbol not found

### ISSUE THREAD

**Issue by peterwaller-arm** [flang-compiler/flang#745]
Reproducer:

```
$ flang -c bad_module.f90
$ flang use_module.f90
F90-F-0000-Internal compiler error. interf:new_symbol_and_link, symbol not found     901  (use_module.f90: 5)
```

Note that this can be turned into a working example by substituting `INTEGER*4` for the type of `i`.

#### `bad_module.f90`

```f90
MODULE bad_module
IMPLICIT NONE

INTEGER*8, PRIVATE :: i

INTEGER*8, PARAMETER :: some_array(2) = (/ (i, i = 901, 902) /)

END MODULE bad_module
```

#### `use_module.f90`

```f90
PROGRAM use_module
USE bad_module
IMPLICIT NONE
END PROGRAM use_module

```

---

I have made a bit of progress investigating this.

In this function during the array constructor `const_eval` was returning a literal `901` instead of a symbol table for an `TY_INT8`, which `mk_cval1` expects:

https://github.com/flang-compiler/flang/blob/d01767099530eb2e3fe2314cf1d7c826877c88fc/tools/flang1/flang1exe/semutil2.c#L6470-L6471

Inside const_eval, the value of the do variable index is returned `p->currval`:

https://github.com/flang-compiler/flang/blob/d01767099530eb2e3fe2314cf1d7c826877c88fc/tools/flang1/flang1exe/semutil2.c#L6180

The issue, I think, is that `p->currval` represents the current value and not a symbol table - I infer this by seeing that currval is incremented by step, so it can't represent a symbol table entry for a TY_INT8:

https://github.com/flang-compiler/flang/blob/d01767099530eb2e3fe2314cf1d7c826877c88fc/tools/flang1/flang1exe/dinit.c#L447

I conclude that `p->currval` should be fed through `mk_cval(p->currval, A_DTYPEG(ast));` so that it can be inserted into the symbol table if the ast type is INT8.

Does that sound correct?

**Comment by gklimowicz** [comment]
@mleair Mark, can you take a quick look at this?

**Comment by mleair** [comment]
Are you proposing to replace line 6180 (return p->currval) with mk_cval(p->currval, A_DTYPEG(ast)))? The const_eval() function returns values, not asts. So, I suggest that you move the proposed mk_cval() call into the caller of const_eval(). Perhaps at line 6471 in semutil2.c  (i.e., ast = mk_cval1(aval, A_DTYPEG(ast));) use mk_cval() instead of mk_cval1(). Note that mk_cval() calls mk_cval1(), so I suspect it's OK to use here.

**Comment by peterwaller-arm** [comment]
@mleair thanks for the clarifying comment, I've done that in #756 and added a test.
