### ISSUE TITLE
MINLOC intrinsic incorrectly returns last minimum rather than first

### ISSUE THREAD

**Issue by peterwaller-arm** [flang-compiler/flang#763]
The following program, synthesized from the spec [0], prints `4` when the value printed should be `2`.

```f90
program p
integer, parameter, dimension(1) :: param_array_minloc = minloc((/ 4, 3, 6, 3 /))
print *, param_array_minloc
end
```

Somehow it's reporting the value as if `back=.TRUE.` was specified.

`gfortran` prints `2` as expected.

Postscript: the incorrect result is given whether or not `parameter` is specified.

[0] ISO/IEC DIS 1539-1:2017, Section 16.9.133, Part 8 "Examples", case (i).

**Comment by peterwaller-arm** [comment]
I've submitted the tests that caught this in #765, which defend the new `back=` feature.

Note that `maxloc` is not affected.

I'm not certain but I think this behaviour was reproducible before the `back=` feature landed.

**Comment by gklimowicz** [comment]
It looks like it was. Thanks, @peterwaller-arm. We're working on this.

**Comment by gklimowicz** [comment]
@peterwaller-arm I believe this is closed, but please reopen if you find otherwise.
