### ISSUE TITLE
Contribution to flang?

### ISSUE THREAD

**Issue by ChinouneMehdi** [flang-compiler/flang#78]
Is the contribution to this project "flang" open to anyone or it's restricted to Nvidia/PGI developers ?

**Comment by AlexisPerry** [comment]
My understanding is anyone can create a pull request, but only NVIDIA/PGI can merge such requests into the master branch after some review process.

**Comment by sscalpone** [comment]
We at NVIDIA are working through our process for accepting pull requests.  I anticipate an answer soon.
