### ISSUE TITLE
Incorrect include

### ISSUE THREAD

**Issue by diorcety** [flang-compiler/flang#79]
https://github.com/flang-compiler/flang/blob/master/runtime/CMakeLists.txt#L43
    include_directories($(CMAKE_CURRENT_SOURCE_DIR)/include)
should be
    include_directories(${CMAKE_CURRENT_SOURCE_DIR}/include)

**Comment by sscalpone** [comment]
Fixed 9dc7d12aec0947fa81a24157f0b7e4b14a576f44
