### ISSUE TITLE
Missing error message for closing subroutine statement

### ISSUE THREAD

**Issue by RichBarton-Arm** [flang-compiler/flang#802]
The following code used to emit a warning message for the bare END statement to the INTERFACE but no longer does so. This regression came in PR#792, I think from [aeedd9a](https://github.com/flang-compiler/flang/commit/aeedd9ad69c0df7fd8a79bcff19f4ec18123daba)

```
subroutine a
  interface
    real function v()
    end
  end interface
end
```
flang used to emit 

> F90-W-0155-END statement for internal procedure should be END FUNCTION

and is now silent.

**Comment by sscalpone** [comment]
It was a warning.  Btw, f18 is also silent.

**Comment by mleair** [comment]
In Fortran 2008, the requirement that END FUNCTION and END SUBROUTINE must mark the end of an internal procedure was removed.

**Comment by RichBarton-Arm** [comment]
Happy with justification that this is not a bug.
