### ISSUE TITLE
Regression - cannot handle reallocatable statements with CHAR on rhs

### ISSUE THREAD

**Issue by RichBarton-Arm** [flang-compiler/flang#803]
Since [this commit](https://github.com/flang-compiler/flang/commit/ee0caf8613fc2d76ce42ea5dff7bd807fc71f378) landed in PR#796, the following example now hits an ICE (default options only needed)

> F90-S-0000-Internal compiler error. string_expr_length: ast not string op

```
PROGRAM pr796_regression
  CHARACTER(1), ALLOCATABLE :: c
  INTEGER :: i = 1
  c = CHAR(i)
END PROGRAM
```
The bug seems to be very localised and limited to the CHAR intrinsic, ACHAR works just fine. The ICE is also not hit when I switch the argument of CHAR to be a plain number like _CHAR(1)_. 

Looking at the code for _string_expr_length_ perhaps CHAR simply needs to be added to the list of special cases?

**Comment by gklimowicz** [comment]
@mleair Mark, can you take a look at this, please?

**Comment by kiranchandramohan** [comment]
@gklimowicz I can confirm that this is working. @RichBarton-Arm you may close.
