### ISSUE TITLE
Flang to LLVM IR?

### ISSUE THREAD

**Issue by davis-matthew** [flang-compiler/flang#858]
This is a really basic and simple question, and I feel a little silly making it a github issue, but how do you get flang to compile to LLVM IR instead of an executable?

I tried running as:
```flang -emit-llvm test.90 -o test.bc```
and received:
```clang-6.0: error: -emit-llvm cannot be used when linking```
but running without -emit-llvm seems to produce an executable rather than a IR bitcode file, as running: 
```llc test.bc```
results in:
```llc: test:1:1: error: expected top-level entity```
and it's formatting/encoding is different than expected.

**Comment by sscalpone** [comment]
Hey @davis-matthew,

Use -save-temps.
```
% flang -c -save-temps ~/tests/hello.f90
% ls -lt | head
total 0
-rw-rw-r--  1 sjs sw      3496 Jan 19 21:32 hello.o
-rw-rw-r--  1 sjs sw      7758 Jan 19 21:32 hello.s
-rw-rw-r--  1 sjs sw      2484 Jan 19 21:32 hello.bc
-rw-rw-r--  1 sjs sw      3358 Jan 19 21:32 hello.ll
-rw-rw-r--  1 sjs sw      2142 Jan 19 21:32 hello.stb
-rw-rw-r--  1 sjs sw      3288 Jan 19 21:32 hello.ilm
```

**Comment by davis-matthew** [comment]
Oh I see, it compiles, links, and cleans all by default, I didn't expect that. Thanks.
