### ISSUE TITLE
Some test cases not running as part of **make check-flang**

### ISSUE THREAD

**Issue by SouraVX** [flang-compiler/flang#899]
I noticed some of the test cases present in test/f90_correct are not running as part of regression **make check-flang**.
To name a few:
acos.f, debug_module_import.f90

**llvm-lit test/  2&> full.log** ---> will produce log, can grep here to see which test cases actually runned. (this is equivalent to make check-flang, just more verbose).

However these can be runned/triggered individually:
**llvm-lit test/f90_correct/acos.f**  -- works just fine.

I found this while adding test cases for debug info.
As I can see from here, that debuginfo tests doesn't require to produce executable or running the executable. 
Just like LLVM we only need FileCheck based pattern matching at IR level and at the object level llvm-dwarfdump can used to dump debuginfo into textual form for FileCheck based pattern matching.
So probably the existing testing infrastructure (make file based) won't be much useful here.

On the other hand adding lit/FileCheck test cases works just fine, but as mentioned above they are somehow not picked up automatically by make check-flang.

@kiranchandramohan Does anybody faced/familiar with this problem before ? 
Once fixed, adding test cases for debug info support will be straight forward.

**Comment by kiranchandramohan** [comment]
@SouraVX I am aware that these tests at the top level are not running. They used to run at some point but after some restructuring, they stopped. The f90_correct directory does not have a lit.local.cfg, so it gets the config from the top level lit.cfg. The top level lit.cfg only has the *.sh file as test files.

What we have in our downstream compiler is a directory called llvm_ir_correct with a lit.local.cfg (which lists all fortran file extensions as test files) and a makefile. I can make a PR if required.

**Comment by SouraVX** [comment]
Yes adding a local **.cfg** file with relevant suffix solves the present problem in hand.
I prepared a small patch, which adds **debug_info** directory inside **test** directory containing **lit.local.cfg** file containing just the **suffixes**(_tested briefly check-flang is able to capture tests and run them_).
The intent here is to make **debug_info** new home for the all the test cases related to debuginfo WRT to flang.
What's your take on this ? Should raise a PR with this and move forward.

**Comment by kiranchandramohan** [comment]
@SouraVX I believe this is fixed with #900 and #910. Closing. Please reopen if needed.
