### ISSUE TITLE
Debug Build Type cannot be built

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#90]
I've built LLVM (release_40 branch, SHA f3d3277bb713bb8aced9a7ac2e9b05c52d2844ee) with Clang from flang-compiler (flang_release_40 branch, SHA 1210030915d1e1441d62eea54976f4ced7f6ad88). For this build I've selected -DCMAKE_BUILD_TYPE=Debug in CMake. Then I tried to build Flang (master branch), also with -DCMAKE_BUILD_TYPE=Debug set in CMake. It failed with following error:
```
[ 36%] Building Fortran object runtime/flang/CMakeFiles/flang_static.dir/ieee_arithmetic.F95.o
fragment covers entire variable
  tail call void @llvm.dbg.value(metadata i32 %1, i64 0, metadata !1064, metadata !1065), !dbg !1059
!1064 = !DILocalVariable(name: "ix", scope: !1060, file: !3, line: 630, type: !28)
!1065 = !DIExpression(DW_OP_LLVM_fragment, 0, 32)
.
.
.
fragment covers entire variable
  tail call void @llvm.dbg.value(metadata i32 %2, i64 0, metadata !1330, metadata !1064), !dbg !1326
!1330 = !DILocalVariable(name: "ix", scope: !1327, file: !3, line: 936, type: !28)
!1064 = !DIExpression(DW_OP_LLVM_fragment, 0, 32)
clang-4.0: lib/IR/Verifier.cpp:4498: virtual bool {anonymous}::VerifierLegacyPass::doFinalization(llvm::Module&): Assertion `!V->hasBrokenDebugInfo() && "Module contains invalid debug info"' failed.
```

WORKAROUND is to set following environmental variables before running `cmake`:
FFLAGS="-O0"
FCFLAGS="-O0"

UNFORTUNATELY, Flang built that way fails to compile many of the source files when started with -g on the optimization level 2 and higher, due to the same assertion as above ("Module contains invalid debug info").
Example workload that fails to build with -g -O2 using Debug Build Type Flang:
https://codesign.llnl.gov/lulesh/LULESH_serial.F90

**Comment by schweitzpgi** [comment]
This bug was filed against LLVM’s SROA. See: https://bugs.llvm.org/show_bug.cgi?id=32687

The LLVM IR passes verification before SROA and fails after SROA in LLVM.

We haven’t had an opportunity to pursue the response as yet.

**Comment by pawosm-arm** [comment]
seems to be fixed now?

**Comment by sscalpone** [comment]
I have not been able to reproduce it for a while; I haven't tracked down what changed.

**Comment by pawosm-arm** [comment]
There were debug related commits recently, and I got the feedback from the field that this bug stopped to occur.

**Comment by schweitzpgi** [comment]
Having flang produce debug information is an active project. There may be some turbulence involved.
