### ISSUE TITLE
Compile OpenBLAS on Apple M1

### ISSUE THREAD

**Issue by antinucleon** [flang-compiler/flang#954]
I am trying to compile a native ARMv8 OpenBLAS with LAPACK with flang in LLVM 12.

The error is like:
```
/opt/llvm/bin/flang -O2 -Wall -fPIC -march=armv8-a  -c -o lsame.o lsame.f
execvp(gfortran) failed: No such file or directory
```
 
Looks like flang is seeking gfortran to compile this file. 

If I provide a rosenta version gfortran, the error is f951 can't generate code for armv8

Is there anyone to help me understand this? I think solving this is a critical step to provide native scipy on Apple M1.

Thanks.

**Comment by AshokBhat** [comment]
LLVM flang project is different from this project (see https://github.com/flang-compiler/flang/wiki for details). LLVM flang project originated at the F18 project and is under development as of Nov 2020. 

This project, which we sometimes refer to as classic flang, does not support macOS (Apple Silicon) yet. Do have a look at the GNU port for Apple Silicon (under development) at https://github.com/iains/gcc-darwin-arm64#readme. GNU port may be the best solution in the interim.
