### ISSUE TITLE
flang1 does not exist error

### ISSUE THREAD

**Issue by wreckdump** [flang-compiler/flang#965]
I build the flang according to the wiki and I am now trying to compile a simple fortran code. But, I am getting the following error message.

```
clang-10: error: unable to execute command: Executable "flang1" doesn't exist!
```

I don't see flang1 or flang2 in the install/bin directory. Did I do something wrong with the compilation stage?

**Comment by michalpasztamobica** [comment]
Hi @wreckdump , building flang according to the wiki is working fine, as we are running github actions on every PR and commit and they work fine. Please consider the possible divergence between your environment and a standard ubuntu-20.04 that we are using, perhaps looking at [latest build logs](https://github.com/flang-compiler/flang/actions/runs/486071083) will provide some useful insights?

**Comment by martin-frbg** [comment]
I just had that happen to me as well - it happens when one accidentally creates the `build` directory underneath `runtime/flang` and tries to build there instead of underneath the toplevel (which is an easy mistake to make, after just having built in runtime/libpgmath)

**Comment by pawosm-arm** [comment]
This is not an actual bug.
