### ISSUE TITLE
Add drone CI to test arm64

### ISSUE THREAD

**Issue by xoviat** [flang-compiler/flang#987]

**Comment by xoviat** [comment]
cc @kiranchandramohan.

**Comment by kiranchandramohan** [comment]
@xoviat Is this something you are planning to do? It would be very welcome.
At the moment we have a post-commit bot (not based on github actions).

**Comment by xoviat** [comment]
Do you have a link for the arm64 driver?

**Comment by xoviat** [comment]
@kiranchandramohan can you set up drone on this repository? Admin permission is required; go to https://cloud.drone.io/ and login with your github credentials and activate flang.

**Comment by xoviat** [comment]
I am not affiliated with drone, but it seems to be the only one that provides arm64 with no additional configuration.

**Comment by kiranchandramohan** [comment]
I believe I have activated now. Let me know if it did not work. Will check tomorrow. 

We have used drone before for f18 ci.

Thanks for your help here.

**Comment by RichBarton-Arm** [comment]
Tagging @michalpasztamobica who set up the current CI using github actions. He may be able to give assistance.
He and I were discussing how to add Arm coverage there and we were going to use packet.net Ampere Alta machines hooked into github actions. It would be interested to see how drone.io compares to that approach.
Thanks for working on this @xoviat

**Comment by xoviat** [comment]
See #993. It's quite simple, one the shell script is written. I just haven't got around to fixing it yet.
